### ISSUE TITLE
Auto-tags for common issues

### ISSUE THREAD

**Issue by AM2i9** [python-discord/meta#106]
There are some issues that come up in help channels that are usually solved by just sending a tag, the person reads it, and the problem is solved.

For example: `'python' is not recognized as an internal or external command`. This problem is answered by the `windows-path` tag, but you need to wait for someone to come to the channel and type the command for it.

It would also be useful for if, say, someone mentions youtube-dl in their question, to automatically send the ytdl tag. This one might not work that well, because someone might say it outside of a question, but it would still be useful.

It would be useful if the bot could read the message, and send the tag itself, based off the error or problem that is given.

**Comment by wookie184** [comment]
I don't think this would be a great idea. For example, somebody may mention `'python' is not recognized as an internal or external command` when helping, if they are mentioning a case to watch out for that they are explaining themselves, in which case sending a tag wouldn't be helpful.

It could be limited to only the person who opened the help channel, but I still think it would have a limited effectiveness, as it may not be very accurate, and false triggers would be annoying (e.g. if you said what you have tried so far in your question and the tag is triggered describing that exacts same thing)

**Comment by jb3** [comment]
We held a vote on this in our staff meeting and decided it is not something we want to implement at this time.

This sort of functionality is either so simple that it isn't useful or so complex that we are just making a half-featured search engine. We'll leave the natural language portion here to people giving help to reparse questions to a relevant tag.
