### ISSUE TITLE
Policy to not crosspost, new Questions should use a thread.

### ISSUE THREAD

**Issue by dlintin** [python-discord/meta#107]
# What?
Add new policy:
- Do not crosspost.
- Coding questions should be answered via threads, so if you ask a new question create a thread out of it immediately.

# Justification
- Improve readability, Easier to give help, etc.

# Implementation
- Applied for Topical Help Channels & Claimed channel.

**Comment by jb3** [comment]
As mentioned in meta, we're not currently ready to roll out threads on a wider basis to the community.

We'll be adding support to our moderation tooling as upstream dependencies add their support, after that we'll see how we can use threads, but I'm not sure if we want to lay out a "policy" for it, we'll see.

For now I'll close this issue, as it'll be revisited once we are ready to enable threads.
