### ISSUE TITLE
Resource Suggestion: py.checkio.org interactive resource

### ISSUE THREAD

**Issue by laundmo** [python-discord/meta#118]
**Resource name**
py.checkio.org

**Resource location**\
https://py.checkio.org/

**Payment type**\
free, signup required

**Why it should be included**\
Seems like a interesting interactive way to learn/improve at python with decent explanations and examples. seems to cover a wide range of topics but i couldn't check those (they're locked until i advance)

**Potential limitations**\
Not 100% a fan of their UI, it looks neat but compromises on performance (im on a older PC right now and get 10 fps navigating their map). there also does not seem to be a way to jump ahead in the tasks/lessons, at least not one thats obvious to me.

**Comment by lemonsaurus** [comment]
We've reviewed this resource in todays staff meeting, and decided against adding it to our resources page.

![image](https://user-images.githubusercontent.com/2098517/196056833-289fdfb6-cbd8-4f38-b86d-b20116700ea3.png)
