### ISSUE TITLE
Adding emoji to category names

### ISSUE THREAD

**Issue by Cypheriel** [python-discord/meta#141]
# What?
Simple. Prepend emoji to category names.

# Justification
Currently, only a small minority of categories have emoji in their names. This is about the extent in terms of variety or appeal concerning channels. Many have suggested that all channels should get emoji, but the conclusion is that this might end up being far too noisy. My proposed solution is only adding emoji to category names.

I, for one, often have trouble finding specific channels I don't typically navigate to. This is especially true during “events”, where new channels have been added and removed during a specific period. A few of such channels I have difficulty with are the bot channels, in the bot commands category. Adding an emoji like `🤖` would help distinguish different categories at a glance, while also adding some color and variation to the (currently pretty grayscale) channel navigation panel without being awfully “noisy”.

# Implementation
Each category could have their own emoji, which ties to the organization of the categories themselves. Categories and their emoji might look like:
`📜 | Information`
`📰 | News`
`🐍 | Lobby`  (The emoji here is debatable, it could be a `🏠` or something of the likes, as well.)
`🗣️ | Discussion`
`☀️ | Summer Code Jam` (Which, is temporary of course, but still thought I'd offer the idea while it existed.)
`🗄️ | Topical Chat/Help` (The emoji here is also debatable.)
`👥 | Open Source Projects` (Could also be a `🌍`.)
`🎫 | Events` (Could also be `🎟️` or `🏆`.)
`🤖 | Bot Commands`
`🎤 | Voice`
`💤 | Python Help: Dormant`

Obviously, a fair bit of these emoji suggestions are up for debate. Even changing a single of the emoji will alter the sort of “mood” created by them. All in all, I think having some emoji would definitely liven things up, as currently it's fairly bland.

P.S: I hope I did this appropriately. 😛

**Comment by MarkKoz** [comment]
A mockup using Discord's UI would be nice to see first.

**Comment by Cypheriel** [comment]
Hi, I spent some time creating a "clone" of Python Discord. This is just about as accurate as I had the will for it to be, but I think it serves its purpose. The main difference here is obviously the emoji in the category names.

**Dark Theme**: https://imgur.com/a/4MXAILQ
**Light Theme**: https://imgur.com/a/BSAyUrt
**Collapsed**: https://imgur.com/a/eavERM1

**Comment by Akarys42** [comment]
I don't hate it, maybe we could discuss it during the next staff meeting?

**Comment by Leterax** [comment]
Have you checked how this would look on mobile devices? I remember at some point that was an issue

**Comment by janine9vn** [comment]
ooooh, I love how it looks! Provides a nice anchor spot for each category to make it easier to recognize

**Comment by laundmo** [comment]
Staff meeting has spoken, will be done soon:
![](https://img.laundmo.com/u/15ULaI.png)

**Comment by janine9vn** [comment]
This is now done! I changed around some of the emojis to avoid duplicates and make it fit slightly better.
Staff was overwhelmingly in favor of the palm tree for the t(r)opical channels.

Thank you for the suggestion!
