### ISSUE TITLE
dontasktoask dm warning message when someone tries to use the dontasktoask link

### ISSUE THREAD

**Issue by grimmtotal** [python-discord/meta#144]
### Tag Name

Don't ask to ask warning

### What kind of content should the tag include?

An Idea for when someone tries using the dontasktoask link, the current filter just deletes it without warning. I think it would help people better understand why it isn't allowed if it dmed a short message explaining why it isn't allowed. Would love to hear feedback on this idea.

**Comment by mbaruh** [comment]
Hi, thanks for the suggestion. The current filtering system doesn't support such customization, but the one under developement at the moment will, so that's something that's being worked on.
