### ISSUE TITLE
Block use of **all** emoji reactions on #python general channel

### ISSUE THREAD

**Issue by miwojc** [python-discord/meta#149]
### What policy should be amended, and to what?

On #python-general channel only selected users can use reaction emojis. This feels like some people have more privileges than others. I understand that emoji reactions was abused and it was blocked for 'normal' users. However i don't see any reason the emojis are being used by those people that use them (i think admins), other than showing off that 'i can do stuff you can't'. This doesn't create equal and welcoming community. Therefore i propose to block the use of emojis reactions on #python-general completely, so no one can use them.

### Why do you think this policy should be amended?

explained above

**Comment by jb3** [comment]
We discussed this in our staff meeting and decided that for now we'd be keeping permissions as they are. Most usage of the reaction feature is for Helpers to simply upvote a message or add a wave when someone says hello.

We will look at whether we can open reactions up further in future and mitigate abuses in a way other than disabling reactions for all users, we're currently thinking that a denylist of particularly egregious emotes (e.g. middle finger emote) combined with a ban on external emotes (we have a decent enough selection in the server including emotes for upvoting messages). We'll discuss this internally and raise bot tickets if we decide that this could be something we can implement, we may be constrained by Discord ratelimits which are particularly harsh around reactions, so building anti-spam rules for them is difficult.
