### ISSUE TITLE
`!subscribe` adjustments to allow for sub-roles

### ISSUE THREAD

**Issue by janine9vn** [python-discord/meta#150]
### What feature are you proposing?

I would like to re-think how our current `!subscribe` interaction works to allow for more sub-roles that we can ping for announcements.

There are a couple of options here which is why I'd like the input for the larger community:

**Option A** - `!subscribe` subcommands.
`!subscribe` would still keep the current behavior. `!subscribe pyweek` would add the appropriate PyWeek role. We can continue adding in sub-roles as sub-commands as we need them.

**Option B** - Components
We change `!subscribe` to use discord components. Each role would have a button that people can toggle to opt in and out of. This changes the current interaction required from users but would be much nicer in terms of opting in and out of multiple roles. Plus, who doesn't love buttons?

**Option C** - Slash Commands
This is likely not to happen, but I figured I'd put on the table for completeness. We add in slash commands so people can pick from a list of what they want to be notified for. Pros: It's really nice interface for this kind of thing. Cons: We'd have to find a library to incorporate and add another major dependency. 

### What is your justification for the proposed feature?

I would like to add a `@PyWeek Participant` or `@PyWeek Announcements` role that people can opt-in for to receive announcements specifically for PyWeek. Pinging the `@Announcements` does not make sense for all PyWeek announcements as part of the information is only relevant to people who are actively participating in PyWeek and, during the judging phase, have submitted an entry.

**Comment by ChrisLovering** [comment]
I like option B too, I think we just store a list of roleIDs that are self assignable, and have the command render those to names and then put them in the button.

It's fairly simple with d.py to have the current state show in the buttons and have them change on click after assigning the role

**Comment by HassanAbouelela** [comment]
For things that are already in d.py v2, that's fine, I'm just thinking if we need to add another framework for it, let's get another bot.

**Comment by bsoyka** [comment]
Option B seems like it'd be the simplest in terms of user experience, and it would also work fairly well in terms of "backwards compatibility" with anything saying to use `!subscribe`.

This also relates to the idea of using another bot, since a new bot would likely require another prefix and cause some confusion from old instructions. It's probably easier to actually switch to v2.0 than to make a new bot entirely and likely end up combining them again later on.

**Comment by jb3** [comment]
We decided that we will pursue option B in tonights staff meeting.

Once we've migrated to Discord.py 2.0 in python-discord/bot#1815 we'll be able to implement this feature, so we can open issues now pending that migration.
