### ISSUE TITLE
Localization of Cooldown message

### ISSUE THREAD

**Issue by Arthur-Milchior** [python-discord/meta#151]
### Amendment type

Content Update

### Content type

Other

### Please provide the location of the content

Cooldown channel

### What amendment do you think should be made to this content, and why?

The #cooldown channel has a slight issue.

> To find your open channel look through your recent DMs with @Python or use the Discord Search feature in the top right of your screen to search `from:YourUsername` in order to find your most recent messages.

The trouble is that Discord is localized. Meaning that "from" as a special meaning only if Discord is configured in English. In French (my mother and computer tongue), you must type `de:YourUsername`. 
When I entered "From:Arthur" it didn't work.
Admittedly, it took less than 30 seconds to understand the issue and correct it. But I suspect some people less used to Discord may be confused and I suggest updating the message with something such as

> search `from:YourUsername` in order to find your most recent message. If it does not work, you may have to replace `from` by the localized equivalent depending on the language in which discord is configured.

Regards,
Arthur

**Comment by jb3** [comment]
I made this change a few days ago but forgot to update this issue!

Thank you for raising this, it's a good point that I completely forgot when I wrote that message up. I've changed it to the following:

> To find your open channel look through your recent DMs with @Python or use the Discord Search feature in the top right of your screen to search `from:YourUsername` in order to find your most recent messages. You may need to translate `from` to your selected Discord language to be able to search.

**Comment by Arthur-Milchior** [comment]
Thanks for taking my remark into consideration.
