### ISSUE TITLE
Add ability to highlight/track specific words or phrases through DMs

### ISSUE THREAD

**Issue by Harmon758** [python-discord/meta#152]
### What feature are you proposing?

The ability to specify words or phrases and get direct messages notifying when someone in the server sends a message using them.

The idea is inspired by Danny#​0007's Highlight bot in the discord.py server, which after a user uses a command like `!highlight add numpy`, will DM that user whenever a message with "numpy" (case-insensitive) in it is sent in the server. It links the message and channel in the DM, tells you what the highlighted word was, and provides the timestamp, author, and message content, as well as context in the form of other messages around it. You can also remove highlights, see your highlights, and block and unblock specific users from triggering your highlights. It also doesn't DM you when it sees that you're already typing in the channel soon after the message was sent.

To address user privacy concerns, an opt-out could be implemented for anyone who doesn't want their messages to trigger highlights.

If there are issues with DM rate-limits, limitations could be placed on the amount or type of highlighted words or phrases and/or DMs could be sent in batches to a specific user when they get many highlights at once.

### What is your justification for the proposed feature?

A specific use case for this is allowing people with specific knowledge about a library to get notified when someone is asking for help with that library in one of the help channels. Right now, it's difficult for anyone to provide specific help like that, as it's usually not feasible to monitor every help channel to do so within 30 min.

Another example use case might be tracking discussion about a specific PEP that one is interested in.

There's a lot of other possible uses, given the open-ended nature of the feature.

See also [recent relevant discussion in #community-meta](https://discord.com/channels/267624335836053506/429409067623251969/902234092693749800).

**Comment by minalike** [comment]
Apologies for the very late update: this proposal was brought up a couple times during staff meetings, and while an interesting idea, ultimately we had decided the benefits did not seem great enough for us to pursue this.

Thankfully though, with the advent of forum channels coming soon™️, users that are looking to help out in certain topics will benefit from the tags feature that forum posts have natively.
