### ISSUE TITLE
Suggestion to Increase the members in Voice channels

### ISSUE THREAD

**Issue by SibtainCOdr** [python-discord/meta#153]
### What feature are you proposing?

Something has to be done to encourage more people to join voice-based channels. The Server is quite big and thousands of people are ready to provide help in text-based channels, However, the voice-based channels are deserted and hardly anyone joins them during daytime in eastern countries. Like at 6:00 p.m. ist I see some people join the VC's but other than that they are vacant.  Some suggestions Maybe you should inform more people how to get voice-verified and stuff, maybe you should appoint some members who will join VCs and talk there because people will join VCs with people in it rather than an empty one.
If this problem is solved the server will reach its "True Potential" 

Thank you
sibtaiN#6213
timjerry123@gmail.com

### What is your justification for the proposed feature?

I am from India and an active user of the python discord server. I have been on the server for almost half a year and I have noticed that members join VC only from 6:00 p.m. (ist) onwards. There should be done something to encourage members from eastern countries to join vc's. Maybe they don't know how to get voice-verified or something else. If you can solve this problem the servers' reach will become so good, you just have to make sure that everyone knows what voice-verification is and boom, the VCs will be flooded with people. Please take my request into consideration.

Thank you

**Comment by HassanAbouelela** [comment]
Hi, thanks for your suggestion!

What do you have in mind for this? Currently, we send a DM/ping explaining how to voice verify when someone first joins a voice channel, and people are generally directed to there when they ask.

**Comment by SibtainCOdr** [comment]
Thanks for your reply,

I think the rules that are mentioned in the #voice-verification channel are
pretty confusing like this one "Have been active for over 3 ten-minute
blocks. This means you need to have sent your messages over a span of at
least 30 minutes."

Some members don't understand this sentence and they drop the idea of
getting voice-verified, which in turn stops the growth of the server.
In my opinion, there should be a video-based tutorial on how to get voice
verified, and the video should involve the use of cool elements,
show step-by-step instructions, and be easy to understand. We have to keep
that in mind anyone should understand that video.

All the other requirements for voice verification are flawless :)
And you should ask other members to give suggestions about what we should do

Thanks
SIbtain

**Comment by HassanAbouelela** [comment]
There is one step, I'm not sure what the video would show. I guess the core of your suggestion is to reword the instruction?

**Comment by SibtainCOdr** [comment]
You Just have to reword the last instruction, others are flawless

**Comment by HassanAbouelela** [comment]
We've bikeshedded a lot over that requirement. It's difficult to find something succinct. If you have a better suggestion, feel free to make it directly.

**Comment by SibtainCOdr** [comment]
please put that video idea into consideration

**Comment by HassanAbouelela** [comment]
A video is not a small task, and it isn't easy to maintain. I still don't understand what the video is supposed to show because there is only one step to perform.

**Comment by HassanAbouelela** [comment]
I believe that's what I'm doing here. We've had feedback from the staff team, and we've had feedback from people using it from time to time. If you don't have any specific suggestions, that's ok, but there is nothing further to discuss.

**Comment by SibtainCOdr** [comment]
Are you from the staff team ,if yes please let me know your discord
username :)

**Comment by HassanAbouelela** [comment]
Scaleios, you can continue this in the community-meta channel if you wish.

**Comment by dementati** [comment]
For reference to other readers, the current rules are:

One must:
• Have over 50 non-deleted messages in the server
• These messages cannot be in bot-commands or sir-lancebot-playground
• Have joined the community over 3 days ago.
• Have been active for over 3 ten-minute blocks. This means you need to have sent your messages over a span of at least 30 minutes.

**Comment by lxnn** [comment]
Hello,

Thanks for submitting this issue! 

I have to say, I'm not convinced that people being unable to verify is the reason for the low activity at those times. Although this is something that could be investigated. Perhaps we could informally survey a selection of people who meet the criteria but have not verified to find out why.

My feeling is that it is more about having some initial activity for the channel to grow around. I think most people are unlikely to join a VC unless it's already active or they expect others to join around the same time. So perhaps somehow encouraging people to meet up in the VC at a scheduled time each day might be a solution. 

It would also be good to find out whether there is currently demand for this. I.e. whether there are people in these time-zones who are eager to get involved in conversation in the voice-channels who currently do not due to the lack of activity. Does anyone have any suggestions for how we could gauge this demand?

**Comment by lxnn** [comment]
A couple of graphs from the meta-channel discussion.

Server-wide messages by hour over Oct 18-20:
![](https://cdn.discordapp.com/attachments/429409067623251969/904744303602061333/unknown.png)

Filtered to voice category:
![](https://cdn.discordapp.com/attachments/429409067623251969/904744601670254622/unknown.png)

Times in UTC.

**Comment by SibtainCOdr** [comment]
I think you have a better idea than me and i think that we should do the
same thing, maybe get some volunteers to join vc's at a certain time and
that will attract more people's attention.

**Comment by minalike** [comment]
I think one of the great characteristics of Discord voice chats is their spontaneous nature. I would suggest joining when you're free, even if no one is there and more often than not, others will come and join you. If the members that join enjoy each other's company and grow a rapport, that time slot will naturally become a "regular" and active vc hour.

**Comment by minalike** [comment]
We are in agreement that making intentional efforts to stimulate voice channel activity (beyond what they would naturally be) throughout the day is not something that we wish to do.
