### ISSUE TITLE
Keep !helpdm setting on for users that toggle server DMs on & off

### ISSUE THREAD

**Issue by minalike** [python-discord/meta#155]
Re: PR python-discord/bot#1629 and [discussion on server](https://discord.com/channels/267624335836053506/635950537262759947/900958331324223539)

Currently when a user runs the `!helpdm on` command and subsequently closes their server DMs, when bot's DM fails to deliver [the user is then set to not receive help DMs](https://github.com/python-discord/bot/blob/main/bot/exts/help_channels/_cog.py#L594-L608). The user has to remember to rerun the `!helpdm on` command again after re-opening their server DMs at a later date.

This is cumbersome for users who frequently toggle their server DMs on and off. 

It would be nice to disable this behavior and find a way to keep the setting as is even when bot's DMs fail to be delivered to the user.

Currently the bot also pings the user in `#bot-commands` when a DM fails to send, but it is deleted so quickly that I never noticed. We could consider not deleting this message, or extending the amount of time before deletion to give a user a chance to actually see the message.

**Comment by hedyhli** [comment]
This feature (turning of helpdms after hitting an error) is added in python-discord/bot#1642, which uses `bot.constants.RedirectOutput.delete_after` for deleting after a short period of time. In [`config-default.yml`](https://github.com/python-discord/bot/blob/69fdd3649e2f9a646b97e445bc4d5440440e5890/config-default.yml#L524) it's set to 15 (seconds). As someone mentioned in #dev-contrib a few days ago, it was to fix python-discord/bot#1640 "403 Forbidden" error when attempting to send DMs to users who have it turned off.

If we were to keep the setting on after hitting the error, we could possibly just ignore the error, but it isn't a good idea when users who have this feature on don't know they had to turn on their DMs. Perhaps a better solution is to not have it auto-delete after a period of time, instead, having a trash can emoji or with discord UI button so the user can manually remove the message.

**Comment by minalike** [comment]
I'll go ahead and close this issue as I believe I might have been the only user that really wanted it, and I've since found a workaround.

The added complexity with avoiding excessive 403 errors seem not to be worth it.

The idea of extending the period of time before messages are deleted in #bot-commands or transforming it to be deleted via trash can emoji reaction can be raised in another separate issue if we so wish.
