### ISSUE TITLE
Learn By Example

### ISSUE THREAD

**Issue by Sn4u** [python-discord/meta#160]
### Resource type

Book

### Where can the resource be found?

https://www.learnbyexample.org/python/

### What sort of content is in the resource? What areas of Python does it cover?

[https://www.learnbyexample.org/](url) is an online reading resource intended for beginners, which tackles many python concepts in simple and easy to follow sections. The resource is not a comprehensive deep dive into each topic, but merely an easy to understand introduction to them. Notable subjects covered are:

- Data structures
- Control flow
- Functions
- OOP
- Built in functions
- Commonly used methods

As opposed to `[Automate the Boring Stuff with Python](url) which can be very dense with code and exercises, Learn by Example provides concise information often followed by examples and illustrations. The text frequently features links to other parts of the guide so that you can easily backtrack in case you get lost in an explanation to something you haven't learnt yet. 

### Please give any additional information about the resource you think is worth including

The resource is free and features a section about SQL, which may also be something to consider.

**Comment by Preocts** [comment]
Bare except examples and no mention of context-managers for file I/O makes a rooCry.

Beyond those two mild nits, this is quite easy to read and navigate. For quick reference, I'd happily refer someone to this site. Where Automate the Boring Stuff gives the reader a path to follow, this resource slides in nicely as reference.

**Comment by Akarys42** [comment]
I'll disagree with @Preocts on navigation. The full screen ads and having them pop right in the middle of the page really hurts the navigability of the website.

I haven't looked too much at the content, but from what I could see it seemed very barebone.

**Comment by Preocts** [comment]
@Akarys42 I was defeated by my own browser preferences and Malwarebytes doing its thing.  I have to agree, those ads are very obtrusive. 👎🏽 

Shame too, without them the layout is really nice.

**Comment by Sn4u** [comment]
I didn't see the ads either. I'm going to close this based on the fact that it truly is awful with all of the ads in your face
