### ISSUE TITLE
Sort and group help-channels by topics

### ISSUE THREAD

**Issue by pakkinlau** [python-discord/meta#161]
### What feature are you proposing?

Step1: User go to one "available-help-channel" and required to input their topics
Step2: After they specify their topic + questions, the channel will shift to the related help-category.

the preview would be : 

-- occupied-databases-help
 ---help-honey
 ---help-raman
-- occupied-basic-python
 ---help-apple
 ---help-suger

### What is your justification for the proposed feature?

For Helpers: they can work on their specialized areas , or focusing to practice their concepts in those topics.
For Help-seekers: they could have a higher response rate to get help from volunteers.

**Comment by HassanAbouelela** [comment]
Hey, thanks for the suggestion

We’ve actually considered the idea at depth previously, but the truth is, people already struggle with the help system (my DMs can attest to that), so we’re very selective about what we do with it. Adding another step (especially if the asker is a beginner who might not understand what the categories are) isn’t something we’re interested in.

If however you are interested in helping with specific topics, your best bet at the moment would be the topical channels.

**Comment by wookie184** [comment]
This is no longer relevant as we have moved to a help forum. Tags can be added to posts for this purpose
