### ISSUE TITLE
Add more Discord libs to `!docs`

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/meta#163]
I propose we add more Discord libraries to the `!docs` command, now that they are growing in popularity and being used in place of the outdated discord.py

The libs I propose are added are:
- disnake
- hikari
- nextcord

Why not py-cord?

Pycord provides - without the ability to disable - components in the `discord` namespace (including in sphinx), which would lead to collisions with the OG discord.py

**Comment by mbaruh** [comment]
Was actioned shortly after the conversation.

**Comment by onerandomusername** [comment]
Was hikari added?
