### ISSUE TITLE
Programming Pedagogy Channel

### ISSUE THREAD

**Issue by mazalkov** [python-discord/meta#164]
### Channel Name

programming-pedagogy

### What is the channel about?

A place for educators and learners to discuss the learning behind programming 

### Channel type

Discussion

### What justification do you have for the new channel? What do you see it being used for?

This was suggested by a mod, minaberry, and received a lot of praise and interest from myself, Ned Batchelder and some others. When suggested in the community-meta channel, a few people also expressed they want something like this. 

The channel would be used for people to discuss the pedagogy of learning and teaching programming, something I think is of particular value to the server due to the large number of beginners. It would also be a self-serving resource, as discussions in the channel may ultimately benefit the community through changes in teaching style (if and where needed).

![image](https://user-images.githubusercontent.com/32670729/146767623-0a0e6615-19b6-4a05-8a18-8ad679b47e3d.png)

I understand that the main issues would be:
1) Getting enough interest for the channel to be active
2) Moderating the channel if there is enough interest from above
3) Keeping the channel on topic as pedagogy is a very broad field of interest

Hopefully a trial run would show that these potential risks are ratio'd out by the benefits they provide.

**Comment by jb3** [comment]
Note for staff: please also see the existing internal ticket on this suggestion python-discord/organisation#374.

**Comment by mbaruh** [comment]
Just as a side-note, the idea is credited to @swfarnsworth

**Comment by swfarnsworth** [comment]
For interest's sake, this is my internal proposal. I haven't read the discussion you're referring to in community-meta, but I assume mina's mentioning of the idea is a reflection of my proposal.

\***

This is a proposal for a new discussion channel to discuss programming education. Given how many of our users are involved in helping others with programming, I think this would give home to a lot of enjoyable discussions that are currently without one.

### Potential discussion topics
- Is x a good approach for teaching OOP?
- How does the legacy of C-style languages affect how x aspect of Python is taught?
- How important is it for a programmer to learn some amount of assembly?
- Is it better for someone to learn concept x before concept y?

### Responses to anticipated objections
- **"Pedagogy" sounds very arcane.** -- That could just as well be a feature to prevent off-topic discussion. I'm open to alternatives that aren't easily interpreted to mean "this is a channel where you can be educated about programming (ie receive need-driven help)".
- **Zig can see a lot of conversations about whether it's ok to tell people to go google stuff, although he thinks it's a nice idea.** -- If this were reframed as "at what point will it contribute more to someone's learning to suggest that they try to figure it out using Google?", I think it's a worthwhile topic. In either case, the purpose of the proposed channel is not to debate about our policies.
- **We already have a lot of channels and the alleged benefits of this channel don't outweigh its contribution to our channel bloat.** -- This is a valid opinion that I can't dissuade one from holding.

\***

In reference to the OP for this issue, I don't necessarily envision that the channel would be useful for beginners in particular, as the goal is to facilitate discussion among those with enough knowledge of the language (and programming in general) to teach it, though as with any other public channel, anyone is free to participate in any channel.

**Comment by minalike** [comment]
Please see our most recent #changelog announcement, the channel has been born :)
