### ISSUE TITLE
Using domain aliases in channel descriptions

### ISSUE THREAD

**Issue by doublevcodes** [python-discord/meta#166]
### Amendment type

Content Update

### Content type

Other

### Please provide the location of the content

Multiple channel descriptions

### What amendment do you think should be made to this content, and why?

# Background

So, in multiple channel descriptions there are links to content on external pages such as the links to https://github.com/python-discord/meta/issues/new and https://www.pythondiscord.com/pages/guides/pydis-guides/off-topic-etiquette in the `#community-meta` and `#ot.*` channels respectively.

# Proposal

My proposal is that you try to shorten these URLs wherever possible so that there’s more chance that the channel description fits on smaller screen sizes. Obviously, it still won’t fit on every screen size, but it might make it fit on more. To clarify, this means making references to pythondiscord.com, becoming pydis.com, and github.com/python-discord can become git.pydis.com.

**Comment by DMFriends** [comment]
I don't see why this is a problem, @doublevcodes. Users can always click on the channel description to expand it so the entire thing can be seen, like the screenshot below.
![image](https://user-images.githubusercontent.com/86751519/150701446-425b712c-57f5-42dc-a6a1-e2128f846d91.png)

What we could do is add **[Click to expand]** to the beginning of each channel description. I think that's a better idea.

**Comment by bsoyka** [comment]
I think shortening the URLs where possible is a good idea, and there's not really a reason *not* to.

Plus, adding text like that to the start of every single channel description seems like it would just take up more space overall, pushing away potentially important details for those who won't actually click it.

**Comment by DMFriends** [comment]
> Plus, adding text like that to the start of every single channel description seems like it would just take up more space overall, pushing away potentially important details for those who won't actually click it.

Hmm, ok. I see what you're saying. What I don't get is - if we do add that text to every single channel description and bold it, I wouldn't imagine someone not clicking it though, but it depends on the person.

I still sort of disagree about there being no reason not to shorten URLs. 1) if we use a link shortener like bit.ly if you're familiar with that, some people may not know what that link is and decide it's unsafe to click it. For instance, in "The Coding Den" Discord server, they outright ban posting links obfuscated by link shorteners altogether. And 2) in order to actually click the links (regardless whether they're shortened or not), you still need to expand the channel description and only then you can actually click the links.

This is only my opinion on the matter, though.

**Comment by bsoyka** [comment]
The suggestion here isn't to use public link shorteners such as Bitly, though. These are domains we already run that are visibly our brand. This about sums it up:

> To clarify, this means making references to pythondiscord.com, becoming pydis.com, and github.com/python-discord can become git.pydis.com.

Plus, the reasoning behind this suggestion is not to make the links any better to click on, but to allow a bit more information to show in the preview given before clicking.

**Comment by DMFriends** [comment]
> The suggestion here isn't to use public link shorteners such as Bitly, though. These are domains we already run that are visibly our brand. This about sums it up:
> 
> > To clarify, this means making references to pythondiscord.com, becoming pydis.com, and github.com/python-discord can become git.pydis.com.
> 
> Plus, the reasoning behind this suggestion is not to make the links any better to click on, but to allow a bit more information to show in the preview given before clicking.

Ohhhkay, that changes things a bit. I guess I need to read the posts more carefully next time 😀

So if that's the case, then yeah I think that might work fairly well. I mean, this is something that can always be reverted if it doesn't go right, so I actually think it's worth a try now that I think about it.

**Comment by lemonsaurus** [comment]
I see no reason not to do this. Handling it now:

URLs shortened on:
- [ ] Off-topic channels
- [ ] - [ ] Off-topic channels
- [ ] - [ ] Off-topic channels
