### ISSUE TITLE
Rewrite of the how-to-get-help channel

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/meta#174]
The current wording of the how-to-get-help channel emphasizes the mechanics of the help system, which may have been intended to bridge peoples understanding when the dynamic help system was first introduced. I think at this point, our words are better spent guiding the user towards asking a good question and anticipating "collisions" (that is, where two users attempt to claim the channel). The latter part may not be an issue depending on what help system architecture we come up with if we migrate to a forum channel-based system.

Here's the proposed rewrite:

----

// diagram of help channels moving goes here

# How to get help

Send a message with your question in an available help channel. **Be specific about what you need help with**, including a code example and the error message (if you got one), so that people can know what they need to do to help you. The channel will then be just for your question, and will be available until you use the `!close` command or it becomes inactive.

Sometimes, two or more people will try to use the same channel. The bot will say who the channel belongs to; if it isn't you, kindly copy, delete, and re-ask your question in another available channel.

// "currently available channels" message goes here

----

I think brevity is important for making sure people read it, so there are some details that I don't think make the cut, including the existence of the topical channels and the links to the guides on the website. I also think it's important that the channel flow diagram be at the top as I think the channel is probably read from the bottom up, and understanding the diagram requires less attention than the text.

Some phrases ("will then be just for your question") read a bit oddly, but I wanted to use the simplest words possible, as our users have varying degrees of English proficiency.

I apologize for the excessive use of "I think" in this proposal. Perhaps if I were more sure of myself, I would state all my opinions/speculations as fact.

**Comment by wookie184** [comment]
It has been rewritten since we moved to a forum channel and the all the points raised here seem to be either implemented or no longer relevant.
