### ISSUE TITLE
Add a bot that displays active help channels sorted by time since last message and activity in the channel

### ISSUE THREAD

**Issue by moritzvonberg** [python-discord/meta#177]
### What feature are you proposing?

I think there should either be

- a channel called something like #active-help-channels or something to that effect with a list of active help channels sorted by time since last message (and maybe other parameters) updated at a reasonable frequency

or
- a bot command to do the same thing

I think the help channel is probably the better idea simply because of visibility, though the bot could enable more fine-tuned filtering.

It could also possibly add the topic of the discussion by searching for keywords or just copying the first few messages up to a certain length.

I would be happy to develop the feature myself if someone can point me to the right place to make a corresponding PR etc.

### What is your justification for the proposed feature?

IMO from the perspective of people looking to help, it's a bit awkward that the help channels aren't sorted by any useful metric.

Aside from the QOL benefit of possibly being able to identify channels where the person posting the help request simply forgot to close the channel, having a dashboard with keywords or something similar would also make it easier to find issues that people feel like they are particularly equipped to help solve (i.e. libraries they like/use often).

A possible downside is that depending on how channels are sorted, certain questions might be less likely to be answered.

**Comment by DMFriends** [comment]
+1 10000%. But I don't a whole new bot is needed, the existing Python bot should do. Let's see what the mods/admins have to say.

**Comment by moritzvonberg** [comment]
I didn't mean to imply that it needed to be a separate bot, just that it could be added as another command. I think doing *both* might actually be best, since bot commands tend not to be as visible as a channel.

**Comment by DMFriends** [comment]
> I didn't mean to imply that it needed to be a separate bot, just that it could be added as another command. I think doing *both* might actually be best, since bot commands tend not to be as visible as a channel.

I don't strongly agree with that, because when a new bot command is merged it is almost always posted in #changelog on the server which (I assume) most people do check.

**Comment by vivekashok1221** [comment]
Hey!
> a list of active help channels sorted by time since last message

This is currently possible with forum channels, a new discord feature where threads are organized in a forum-like channel. I believe you can filter by creation time as well as recent activity. However, the Discord API doesn't support it yet.

**Comment by ChrisLovering** [comment]
Yea, by default forum channels sort the posts by most recent activity. So this will be solved when the forum channels feature is made generally available and the public API is updated.

**Comment by moritzvonberg** [comment]
Does that mean that at that point you intend to convert the help channels to the forum format when it goes public?

**Comment by ChrisLovering** [comment]
Yep

**Comment by lemonsaurus** [comment]
I think with forum channels as the long-term solution for this, we're probably not going to be jury rigging some sort of temporary solution for this - but I do think it's a highly relevant suggestion. If it hadn't been for Forum Channels, I'd probably be in favor!

By the way, did you know we originally tried to do this by constantly sorting and resorting the channels in order of activity? It was great! Except, it was confusing because the channels kept moving around, and it ended up hitting rate limits. Oops.

I'm gonna close this issue for now, and we'll just wait for Forum Channels to have this problem sorted.
