### ISSUE TITLE
Algorithms Github (Python)

### ISSUE THREAD

**Issue by asterized** [python-discord/meta#180]
### Resource type

Community

### Pricing

Free

### Where can the resource be found?

https://github.com/TheAlgorithms/Python

### What sort of content is in the resource? What areas of Python does it cover?

Inside the Github repository there are a list of algorithms implemented in Python.

**Comment by DMFriends** [comment]
I like that idea. I actually have a star on it 😅

Maybe this issue should be transferred to the site repo so it can be discussed there and if approved, add this resource to the site?

**Comment by swfarnsworth** [comment]
Thank you for making this suggestion. I'm quite impressed with the breadth and code quality of this repository. I'd definitely like to add it to the resources page under algos/data structs and data science.

It doesn't neatly fall under any of our resource types, so it may need to be entered as a tutorial.

@DMFriends we use the issue tracker in this repository for resource suggestions.

**Comment by DMFriends** [comment]
> @DMFriends we use the issue tracker in this repository for resource suggestions.

Oh alright, I wasn't sure.

**Comment by minalike** [comment]
Thanks for your suggestion. It's now live: https://www.pythondiscord.com/resources/?search=the+algorithms
