### ISSUE TITLE
Media manipulation channel request

### ISSUE THREAD

**Issue by Ibrahim2750mi** [python-discord/meta#181]
### Channel Name

#media-manipulation

### What is the channel about?

This channel will be used to ask questions related to manipulating images, audio and video files

### Channel type

Topical

### What justification do you have for the new channel? What do you see it being used for?

Here are some things I can see it being used for:
+ For images it can be used to ask questions related to the lib PIL, opencv-python etc. Will be mainly used for image processing(gradients, cropping, converting to transparent etc )
+ For audio it can be used to ask question related to wav, pyaudio, librosa etc. Will be mainly used for asking questions like processing wav files, creating music etc.
+ For videos it can be used to ask questions related to libs like opencv-python, python-gstreamer etc. Can be mainly used for video processing(noise removal, cropping etc)

**Comment by mbaruh** [comment]
As discussed in a staff meeting on 2022-04-24, there's now a #media-processing channel. Thanks for the suggestion!
