### ISSUE TITLE
Resources: Atom (the editor) is being sunset

### ISSUE THREAD

**Issue by swfarnsworth** [python-discord/meta#185]
The Atom editor [is being sunset in December](https://github.blog/2022-06-08-sunsetting-atom/).

My recommendation is that we simply delete it from the resources page. We already list Mu-Editor, PyCharm, Spyder, Sublime, Thonny, and VSC. I'm not sure which audience Atom is intended to appeal to, but I suspect part of the reason for them sunsetting Atom is that its audience might have shifted to one of the other editors that we feature.

Does anyone know what the value proposition of Atom is, as compared to the other editors? If there is one, I suppose we could change the description to mention that it's going to be sunset and see what happens (Senjan pointed out that it might be forked). Otherwise, I don't think this resource should be featured to reduce the frequency of option paralysis for our users.

**Comment by lemonsaurus** [comment]
I agree that we should get rid of this, we shouldn't be recommending software that's no longer being maintained.

I'm not sure it's worth recommending Sublime anymore either given how poorly it works with WSL2 compared to VS Code, and how much richer the extension marketplace for VS Code has grown. Sublime used to be amazing but I wouldn't recommend it today.

Does anyone actually _use_ Spyder, by the way?

**Comment by swfarnsworth** [comment]
I think the use cases for sublime can be served by VSC or Notepad++.

My friend, who is an ecology PhD student, uses Spyder. I think the target audience is "non programmers who use python for scientific computing".

**Comment by lemonsaurus** [comment]
> I think the use cases for sublime can be served by VSC

![image](https://user-images.githubusercontent.com/2098517/173378273-3bdeccf4-c41d-4d41-a3a6-9089eb9622e6.png)

> or Notepad++

![image](https://user-images.githubusercontent.com/2098517/173378224-d20480ad-2043-4866-ab49-32d140262afe.png)
