### ISSUE TITLE
AI Gaming Competition

### ISSUE THREAD

**Issue by yodigi7** [python-discord/meta#188]
### What feature are you proposing?

Have a new competition where developers can code bots to play games against each other so for example you can code a bot that will play chess and can pit it against another competitors bot. You can use whatever game or even create a new basic game for the competition and then see who does the best. 

### What is your justification for the proposed feature?

This would be another fun competition to add that would allow anyone to join and learn more about python while surfacing some of the best developers. It is a competition that is more centered around algorithms and more backend stuff without needing to deal with any of the frontend beautification hassle most python devs prefer not to deal with.

**Comment by lemonsaurus** [comment]
We've discussed this in todays staff meeting, and while this does sound like a fun event, it's not something we're willing to invest in. Our event calendar is pretty full already, and we're very committed to the events we've already got planned. We don't feel like we have the capacity to commit to another one at the moment.

I will mention that https://rlbot.org/ is a really fun community where you can learn to write AI in Python and pit your AI against other AIs in competitions. I highly recommend looking into it, especially if you've played Rocket League and enjoy the game!

I'm gonna close this issue for now, but thank you for creating it! We're very grateful for all the suggestions we receive.

**Comment by etrotta** [comment]
Kaggle also hosts some competitions of that kind - for example, https://www.kaggle.com/competitions/kore-2022
