### ISSUE TITLE
Multi Language Help Support

### ISSUE THREAD

**Issue by sco1** [python-discord/meta#19]
Programming is a global language! As has been a discussion at least a few times in recent weeks, as the Pydis community grows there's a similarly growing desire to be able to provide Python help to those for whom English is not their first language and are not comfortable enough with it to be able to both adequately present their problem and to understand the help being provided.  There have been at least a handful of recent instances where folks were able to quickly rectify their issue when working with someone who could communicate with them in a language they were more comfortable with.

I'd like to propose a framework for providing language-specific help for those who would benefit:

- Because the primary barrier to providing support for languages other than English is one of adequate moderation, poll staff members (Helpers+) for those who would be interested in providing support and oversight in languages other than English.

- Create an `International Help` channel category. If sufficient support is available for a given language (defined...somehow), open a `#help-lang` channel for that language, functioning more or less identically to the current help channels.
    - There will be a necessary caveat that help will likely take longer in the non-English help channels, depending on the number of users available who speak the language.
    - If it's noticed that significant question overlap begins to happen, additional channels could be opened as we've done with the current help channels. (To be overhauled with the new and improved help system in the future 😄 )
    - Staff's ability to support will be a continuous poll, if sufficient support is unavailable then the channel will be archived until returned to an appropriate level

**Comment by gdude2002** [comment]
I think there are a couple big issues with these suggestions, so I'll lay 'em out.

1. Adding additional language-specific help channels will encourage people to speak not-English in other channels. We simply can't moderate that scale of chat in another language.
2. Since we don't have many users that speak other languages and we can't oversee them ourselves, it's impossible to gauge the quality of the help provided and it's likely we would have way, way more questions than answers.

If we had an actual foreign language userbase, this would be great, but unfortunately (?) we do not.

**Comment by surister** [comment]
>Adding additional language-specific help channels will encourage people to speak not-English in other channels. We simply can't moderate that scale of chat in another language
Well, as long as the users *do not* read the rules/channel descriptions.. I mean you will still have people breaking rules, regardless of the rule. 
> Since we don't have many users that speak other languages and we can't oversee them ourselves, it's impossible to gauge the quality of the help provided and it's likely we would have way, way more questions than answers.
Maybe run some analytics (public poll) and then decide what languages are more demanded, then maybe get some people that are willing to be pinged anytime to translate/offer support.

**Comment by heavysaturn** [comment]
I don't see this working out. we might have helpers who can speak many languages, but we there's no way to ensure we have moderators enough. I've also never really seen any indication that there is a big demand for this. a couple of cases here and there, but never more than a couple.

**Comment by sco1** [comment]
There's some happy medium that exists between the flat out "can't help" that we have now and the cases where special dispensation has been given to get a problem resolved in another language.

I think it lends great value that the capability even exists on our server, regardless of the capacity to adequately support any specific language. Where else are they going to go?

**Comment by gdude2002** [comment]
I don't really disagree that it'd be a nice thing to be able to do, but I really can't see it happening without a solution to the moderation issues.

**Comment by sco1** [comment]
Seems like consensus has been reached.
