### ISSUE TITLE
Typed dict tag

### ISSUE THREAD

**Issue by CaedenPH** [python-discord/meta#190]
A tag explaining `typing.TypedDict` and what it's useful for.

**Comment by swfarnsworth** [comment]
We want tags that answer common questions, where a succinct answer requires a medium level of effort to formulate, and for which that one succinct answer generally applies. Can you explain why you think typed dicts meet these criteria, and perhaps give a draft of what you would want the tag to be?

Keep in mind that `!docs typing.TypedDict` exists, so whatever information this tag would have, it needs to be better than that in some way.

**Comment by minalike** [comment]
@CaedenPH Did you have some tag content in mind?

**Comment by wookie184** [comment]
As mentioned, `!docs typing.TypedDict` gives a pretty good output. I don't think this is worth tracking, though if there's some specific content you think would be helpful feel free to open a new issue.
