### ISSUE TITLE
Pattern matching topical channel

### ISSUE THREAD

**Issue by CaedenPH** [python-discord/meta#197]
### Channel Name

#pattern-matching

### What is the channel about?

Talk about pattern matching including regex and python3.10 `match`

### Channel type

Topical

### What justification do you have for the new channel? What do you see it being used for?

Regex is a large topic, often discussed in `#python-general`, help channels, or off-topic. A single `#pattern-matching` channel can group all questions related to regex, 3.10 match case and other matching algorithms. This organizes the questions to maximise the chance of getting and delivering help.

**Comment by wookie184** [comment]
Python's structural pattern matching and regex are quite separate topics, so I'm not sure it really makes sense to group them together.

In general, I think most questions about pattern matching should be fine in help channels. Unlike other topics, questions about pattern matching usually wouldn't require any special expertise to answer (how pattern matching works is fully documented, all in the python docs).

Regex is different in that a difficult question could benefit from someone with lots of experience, but I think most questions could still go in a help channel. As well as this, regex isn't python specific, so whilst it's fine for help channels, a whole channel for it may be a bit out of scope.

**Comment by wookie184** [comment]
Discussion in `#community-meta` seemed to agree this isn't something we'd want.
