### ISSUE TITLE
Recast on policies completeness

### ISSUE THREAD

**Issue by Nenrikido** [python-discord/meta#20]
**Rephrased by @gdude2002 - for ease of reading**

Hello,

I've come here due to a misunderstanding around the server's moderation policy, which I feel needs to be changed. For example: I've been muted for advising moderators to moderate on some subjects - such as off-topic discussion.

I ended up getting a infraction on a subject not explicitly covered by the rules or enforcement guidelines. Here's my advice: Either...

*  Add some text to the rules to state that the rules aren't intended to be the be-all-and-end-all of the moderation policy and that they may be modified as needed
* State explicitly how staff are expected to handle this type of issue

If you like, I could write something up for you.

Thanks,
Nenrikido

---

**Original**

Hello,
I come here because of some misunderstanding on the policies which i find, need to be changed.
I've been for example muted for advicing moderator to moderate on some subjects like offtopic.
So i got a sanction on something not explicitely said in the policies or on an enforcing of those policies.
What i advice is : Either add some sentences to say that some rules can be reviewed by the staff according to need (and also that the rules aren't ended to be written).
Or say explicitely how staff can handle those kind of issues.
If u want i can tell how and where i'd write it in the policies.
Cordially, 
Nenrikido

**Comment by heavysaturn** [comment]
it should go without saying that the rules cannot be completely exhaustive. Our staff members are free to excercise their moderative powers to ensure the community runs smoothly in whichever way they see fit. 

now, this being said, adding a sentence to our rules about how we reserve the right to moderate outside of these rules at our own discretion if we believe it will benefit the community as a whole would be an acceptable change to me.

**Comment by gdude2002** [comment]
I'm not really against revising the rules, maybe they need to be looked over and rewritten entirely given that it's been such a long time since we've written them.

I do feel like they assume a level of common sense, though - and I agree with @heavysaturn that they cannot be exhaustive.

**Comment by gdude2002** [comment]
(I would also like to point out that the infraction you were given _was_ covered by the rules - See rule 6)

**Comment by Nenrikido** [comment]
(Assuming i wasn't respecting the staff members ?)

**Comment by gdude2002** [comment]
That discussion isn't really suitable for this ticket. One topic per ticket, yeah?

**Comment by heavysaturn** [comment]
it's not an assumption. you were asked to stop backseat moderating, and you kept doing it in spite. to respect the staff extends to doing what they ask you to do.

**Comment by Nenrikido** [comment]
But that was in respect for the staff, as i said to @gdude2002, I wanted to change the policies from start

**Comment by heavysaturn** [comment]
gdude is right - this discussion is not suitable for our issue tracker and not relevant to this ticket.

**Comment by Nenrikido** [comment]
so let's don't follow it and come back on ticket, how should we write it if you agree with it ?

**Comment by heavysaturn** [comment]
I already made a suggestion. beyond that the staff will discuss this internally.

**Comment by Nenrikido** [comment]
Ok

**Comment by heavysaturn** [comment]
This is continued in #21
