### ISSUE TITLE
Whitelist .latex command to help channels.

### ISSUE THREAD

**Issue by kurazl** [python-discord/meta#200]
### What feature are you proposing?

Whitelisting .latex command to the help channels (#help-food channels)

### What is your justification for the proposed feature?

Because computer science in general is math-heavy in certain areas, it would help with clarity to be able to use latex to convey mathematical concepts/equations/etc.

**Comment by wookie184** [comment]
Sounds fine to me, anyone can feel free to open a PR to whitelist it for the help forum.

**Comment by wookie184** [comment]
Implemented by https://github.com/python-discord/sir-lancebot/pull/1230
