### ISSUE TITLE
Correct language about posts using the word channel

### ISSUE THREAD

**Issue by Assile** [python-discord/meta#204]
### Amendment type

Content Update

### Content type

Other

### Please provide the location of the content

Discord Server

### What amendment do you think should be made to this content, and why?

For example in the #❔｜how-to-get-help channel we have the following text:
`
Your channel will automatically close after 30 minutes of inactivity, or if you run the !close command. If your question relates to one of the topics under Topical Chat/Help, you can consider asking there instead.
`
Which I believe would be better worded with `Your post will ...`.

Another example can be found in the help post messages. This was recently discussed in relation to https://github.com/python-discord/bot/issues/1295.

**Comment by Assile** [comment]
Would https://www.pythondiscord.com/pages/guides/pydis-guides/help-channel-guide/#frequently-asked-questions also need to be taken into account for this change?

**Comment by shtlrs** [comment]
> Would https://www.pythondiscord.com/pages/guides/pydis-guides/help-channel-guide/#frequently-asked-questions also need to be taken into account for this change?

What do you think needs to be changed for this? Replacing channel with post?

**Comment by Assile** [comment]
> > Would https://www.pythondiscord.com/pages/guides/pydis-guides/help-channel-guide/#frequently-asked-questions also need to be taken into account for this change?
> 
> What do you think needs to be changed for this? Replacing channel with post?

Yes, that's my thinking. If a 'channel' under a Forum channel is considered a post, then some of the mentions of the word channel here should also be changed to the word post, right?

**Comment by shtlrs** [comment]
> Yes, that's my thinking. If a 'channel' under a Forum channel is considered a post, then some of the mentions of the word channel here should also be changed to the word post, right?

Theoretically, yes.

The thing here is that, technically, it isn't. And that's because these posts are threads IIRC.

There is some nuance between both, and it caused some sort of "confusion" or debate on what they need to be called. And I think channel was chosen because it's they're quite common across users as channels, even though a post is just sort of façade and new way to create a new "channel", which also has a title.

**Comment by Assile** [comment]
> Theoretically, yes.
> 
> The thing here is that, technically, it isn't. And that's because these posts are threads IIRC.
> 
> There is some nuance between both, and it caused some sort of "confusion" or debate on what they need to be called. And I think channel was chosen because it's they're quite common across users as channels, even though a post is just sort of façade and new way to create a new "channel", which also has a title.

Fair enough, do you think this warrants not changing any of the language, or to just keep the language on the help page unchanged?

**Comment by shtlrs** [comment]
> Fair enough, do you think this warrants not changing any of the language, or to just keep the language on the help page unchanged?

I wouldn't say it warrants not changing any of the language, but the language on the help page has been reviewed & I think that was what we had agreed upon. So first instinct would be to have everything in that fashion.

But we can see what others have to say about this.

**Comment by wookie184** [comment]
I don't think this is worth changing, I think "help post", "help thread", and "help channel" are pretty much equally understandable.

The first thing sent when someone creates a post is "Python pinned a message to this channel.", so even Discord itself isn't particularly consistent.
