### ISSUE TITLE
Add tag for users stuck in the REPL

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/meta#207]
Create a tag that summarizes the difference between the shell and the REPL, what each one is used for, and how to "escape" the REPL to get back to the shell.

**Comment by wookie184** [comment]
I think this could be accomplished by improvements to the existing `!repl` tag (#214) though unless the info can be conveyed in a concise way it may make it too long.

**Comment by wookie184** [comment]
Do you still think this is worth it given the new contents of the `!repl` tag: https://github.com/python-discord/bot/pull/2736

I think another tag would end up being a bit repetitive and probably not worth adding, same for https://github.com/python-discord/meta/issues/208

**Comment by shenanigansd** [comment]
That makes sense, I can close this issue
