### ISSUE TITLE
Improve the `in-place` tag

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/meta#213]
### Amendment type

Content Update

### Content type

Tag

### Please provide the location of the content

in-place

### What amendment do you think should be made to this content, and why?

The current `in-place` tag only has an example of wrong uses of in-place/out-of-place functions and only describes correct usage, which can confuse beginners who don't read the comments and assume that it is the correct way of using them. The tag should at least include the correct usage (and maybe get rid of the incorrect usage).

There are also minor errors in the rest of the tag which should be fixed, such as brackets being inside of inline code formatting:
> ... either use an out-of-place operation `(sorted(...))` and assign it to a variable ...

**Comment by wookie184** [comment]
Both suggestions sound good to me, and yeah could probably get rid of the incorrect usage as long as it's made clear why the correct usage is correct.
