### ISSUE TITLE
Improve the `repl` tag

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/meta#214]
### Amendment type

Content Update

### Content type

Tag

### Please provide the location of the content

repl

### What amendment do you think should be made to this content, and why?

The current `!repl` tag is a big wall of text, which can make it distracting and/or daunting for new users.
To improve it, certain parts of the tag could be cut down as they aren't relevant in most contexts (such as the sections that describe `help()` and the `-i` flag).
Adding an example like the following would also make it more approachable to new users:
```py
>>> msg = "Hello world!"
>>> print(msg)
Hello world!
>>> 
```

Another issue is this that this tag is often invoked when a user types a command-line command into the REPL, which this tag does not mention at all. This could be addressed in the tag.

**Comment by wookie184** [comment]
Yeah, the current tag isn't great. A PR with improvements / a rewrite would definitely be welcome.
