### ISSUE TITLE
Add code block preview for the `!code` command

### ISSUE THREAD

**Issue by GhostOps77** [python-discord/meta#215]
### Amendment type

Content Update

### Content type

Tag

### Please provide the location of the content

https://github.com/python-discord/bot/blob/main/bot/resources/tags/codeblock.md

### What amendment do you think should be made to this content, and why?

I've added a preview for the given code block example, given in the `!code` command's embed
This will be very helpful for new-comers to understand, compared to the old description

**Comment by swfarnsworth** [comment]
Thank you for opening this issue.

I am opposed to this change. I think it's important than the tag be as concise as possible, and I do not think seeing an example of formatted code has enough added value to justify its vertical space.

The `!code` message used to be longer and more detailed, but because of its length, the key point (these are the characters you need to type to format your code--please do that) was often ignored.

**Comment by swfarnsworth** [comment]
For your reference, this is the commit from 2020 that abbreviated the message: https://github.com/python-discord/bot/commit/4610483e28100b4f3943612981000a9e8707e802

**Comment by GhostOps77** [comment]
@swfarnsworth Those 3 lines are worth it tho
and making it being too concise, it's just make it difficult for people to understand it

so, it'll be better to have to those formatted code blocks

**Comment by swfarnsworth** [comment]
I think this is a difference of opinion we have that will be impossible to bridge.

The principal difficulty we have in signposting is that people don't want to read--they want to make an immediate judgement about whether or not the sign is relevant to them, and if they think it is, they only want to skim for key points.

We found that after abbreviating the `!code` tag, its instructions were more often followed each time it was evoked. I believe that if we integrate your proposed changes, its instructions will be followed less frequently.

**Comment by GhostOps77** [comment]
I agree, thanks for your guidance

**Comment by swfarnsworth** [comment]
Thank you again for giving this suggestion. I hope you are not dissuaded from giving suggestions in the future.
