### ISSUE TITLE
DevOops meeting coffee

### ISSUE THREAD

**Issue by shenanigansd** [python-discord/meta#216]
### What feature are you proposing?

- ref: https://discord.com/channels/267624335836053506/675756741417369640/1118508462951907328

I was recently made aware that due to the changes to the meetings, pre-meeting coffee would no longer be provided.
This is madness!
The pre-meeting coffee is an _integral_ source of watered down coffee and “water cooler” gossip for the entire team!
Just removing it is completely ridiculous!

### What is your justification for the proposed feature?

I like coffee and gossip

**Comment by jchristgit** [comment]
Good morning,

@HassanAbouelela is our experienced coffee brewer. He will be taking this issue.

**Comment by HassanAbouelela** [comment]
Thank you for bringing this to my attention. We've reviewed the case, and will be implementing a 4-step plan to address the issue.

The plan has been submitted to the PyDis requisition team for approval, and will be implemented as soon as possible.

The bean water will flow.

**Comment by HassanAbouelela** [comment]
The proposal has been approved and actioned. We now have a machine that serves lukewarm coffee in the corner of the meeting room at HQ. We were forced to compromise, but you can use the machine during any meetings you have there.
