### ISSUE TITLE
paste.pythondiscord.com - Issue with code renderer for tabs indentation

### ISSUE THREAD

**Issue by Andrej730** [python-discord/meta#229]
### What feature are you proposing?

Noticed an issue with paste.pythondiscord.com rendering the following code - https://paste.pythondiscord.com/FWIA

![image](https://github.com/python-discord/meta/assets/9417531/4d696bbf-f550-4114-a3aa-155a98fcc1ea)

Original code is using tabs for indentation and it seems the website is interpreting first indentation tab as a space and second and further tabs are just ignored.

### What is your justification for the proposed feature?

paste.pythondiscord.com is used by random people coming to #python-help and they can use tabs for indentation in their code snippets

**Comment by ChrisLovering** [comment]
We use [pinnwand](https://github.com/supakeen/pinnwand) for our paste service. This issue is better discussed with the pinnwand maintainers on their own repository.
