### ISSUE TITLE
Clarifying our DM policy

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/meta#23]
After a recent incident in #meta, I think it's probably a good idea to clarify our position on soliciting for DMs on server. A well-written and thought-out answer in the FAQ is probably better than an explanation we need to come with on the spot. I would do it personally, but writing stuff is not something I excel at, so hence this issue.

My position is:
- No soliciting for DM's on server;
- No random DM'ing of members of our server;

Obviously, if people want to DM each other, that's okay, but that's not the same as posting a message not aimed at anyone with "Hey, please dm me for <reason>".

**Comment by gdude2002** [comment]
It's probably worth pointing out that this _is_ clarified in the "how to get help" document, but it probably could do with being a bit more prominent than that.

**Comment by SebastiaanZ** [comment]
Yes, agreed. Thanks for pointing that out.

Also, this particular incident was not related to getting help, so a more general explanation of our policy is likely not a bad idea.

**Comment by Refisio** [comment]
Maybe this love could spread to the `no-dm` tag on the Bot.
As it stands right now, when the tag is called, the bot will pull a message that is geared specifically towards DMs for tutoring and help. Maybe that could be rewritten as well in order to reflect this clarification.

**Comment by lemonsaurus** [comment]
We removed the `no-dm` tag completely, after seeing it abused one time too many.
