### ISSUE TITLE
Adding roles for the general user

### ISSUE THREAD

**Issue by landizz** [python-discord/meta#25]
I personally would feel like it would be nice to include some more roles obtainable by the general users. I do not suggest adding alot of roles making the whole thing a clutter but instead adding a few roles with meaning and value that users can obtain by meeting certain demands. 

This would add a sense of inclusion in the server and being able to stand out from those that are new or maybe just read the chats but never engages in them. 

Exactly how this would be implemented and what requirements the roles would have, needs to be discussed further. 

A example of a role that could be implemented would be,
"Python Enthusiast"
Color: Will be decided on implementation
Requirements: Post a minimum of 10 posts/day during a period of 30 days without any break in #python-discussion.

This is only an example of how it might look.

I am not suggesting that you start implementing roles left and right without consideration but make only a few (1-2) with a meaning behind it and a value of getting it, and in the future you might add another one based on user demand or whatever.

**Comment by LordHemlock** [comment]
There's a couple issues regarding this:

1. Having a role generated by activity runs the risk of causing a channel turn into a spam channel.  People will want to get a role just for the sake of having it.  

2.  We prefer to have roles that have more meaning than simply activity.  For instance, the Helper role is based not only on activity, but knowledge of the language, quality help, ability to give good examples, patience, and the right attitude and demeanor that represents the best of our server.

If people are looking for roles to collect, I encourage them to participate in our Code Jams or possibly gain the Contributor role by participating on issues in our Seasonal Bot or even our main Bot or Site.  

There are plenty of opportunities to gain roles without us making one just for the sake of having one.
