### ISSUE TITLE
New !scopes command

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/meta#26]
!scopes command does not exist so Lemon told me to make an issue so that it could be added to the list.

I hope the following explanation is adequate. If it is not then feel free to re-write it.

--------------------------------

Scopes
Variables can only reach the area in which they are defined, which is called scope. Think of it as the area of code where variables can be used. Python supports global variables (usable in the entire program) and local variables. By default, all variables declared in a function are local variables.

`a = 'hello

def main():
    print(a)`

This will output the value of 'a' which is 'hello'. This works due to the fact that function can access the global scope which contains the variable 'a'.

`
a = 'hello'

def main():
    a = 'bye'

main()

print(a)`

In this case the value outputted will be 'hello' as variables defined within the local scope and therefore we can not call their value from outside the function. The variable 'a' created inside the function may have the same name as a the variable outside but they are different. This can be proven by printing the memory locations which will be different.

--------------------------------

Probably not the simplest explanation and could use refinement.

**Comment by fiskenslakt** [comment]
Done, the `!scope` tag now exists.
