### ISSUE TITLE
Feature request: topics

### ISSUE THREAD

**Issue by martmists** [python-discord/meta#27]
![image](https://user-images.githubusercontent.com/16361449/51634831-8379f580-1f55-11e9-93fe-5f32c74cf6e3.png)

The basic idea here is to allow any user to easily contribute to a guide, making it easier to understand as time goes on. Topics that are difficult to grasp using official/existing documentation, like Tensorflow and Audio Manipulation, could easily be explained from just basic understanding of python.

[Link to discussion](https://canary.discordapp.com/channels/267624335836053506/429409067623251969/537728984578785280)

Additionally, we could expand this by allowing `.ipynb` files to use [`bokeh`](https://github.com/bokeh/bokeh), if this proves useful.

---

Possible guides:

- Bots
  - Reddit
  - Discord
  - Twitch
- Audio Manipulation
- AI
  - PyTorch
  - Tensorflow
  - Implementation differences in learning methods
- `struct` module and applicances
- APIs
  - Basics
  - Integrating DBs
  - Ratelimits, etc.
- "Proper Code Style"
  - Introduction to PEP 0008 and why it is so important, despite being different for everyone
  - Useful CQA tools/inspection
- numpy/scipy
  - documented use of all features and purposes
- etc

**Comment by lemonsaurus** [comment]
We have discussed this internally and there may definitely come a time when we'll allow non-staff to submit proposals for wiki articles - but it's not something we're going to be doing very soon. Thanks for the suggestion, though.

Meanwhile, if anyone really wants to see a guide in our wiki, feel free to submit a guide proposal as an issue here in this repo, and we will consider adding it for you. The wiki uses markdown, just like GitHub, so formatting will be mostly intact.
