### ISSUE TITLE
Issues Command

### ISSUE THREAD

**Issue by RohanRadia** [python-discord/meta#29]
Hey staff,

Lemon has already told me that the bot is under 'lockdown' and is not currently having features added to it but I wanted to suggest one for the future.

In channels such as seasonalbot chat I believe we should have the ability to run the command `!issue <#number>` and the bot posts the link to the issue. The reason for this is that often we are talking about some ideas or a specific issue or several interlinking issues and we have to stop talking to find the link of it and post it in the channel. Most people know the number of the issue they are working on and this command would help to streamline the process of referencing different issues/tasks. 

Just a suggestion, not sure if this is something you guys want to implement.

Many thanks,

Rohan

**Comment by jodth07** [comment]
I do like that idea. and perhaps we can consider implementing once the lock down is release.

**Comment by jchristgit** [comment]
Sounds good, but wouldn't this just be linking `https://github.com/python-discord/{repository}/issues/{n}`?

**Comment by RohanRadia** [comment]
Yes it would. If you look at SB chat today we have been referencing issues but so many times we have had to stop, get the link etc. This would allow us to speed up and streamline the process.

**Comment by lemonsaurus** [comment]
issue numbers aren't unique across the whole org, just for that particular repo. so unless you wanna type `!issue seasonalbot!#42` or something, how would it know which repo to look in for the issue?

I think perhaps this could be a seasonalbot feature that fetches seasonalbot issues, perhaps with the other repos as optional subcommands. So, `!issue 42` would fetch 42 from seasonalbot, but `!issue site 42` would fetch it from site.

it'd also be nice if it wasn't so naive that it would post a url to a page that didn't exist. it should instead give an error in a nice embed, like most of our features do.

**Comment by RohanRadia** [comment]
Your command idea looks perfect. I am happy to take this on. Let me know.

**Comment by scragly** [comment]
@RohanRadia if you're willing to make an issue outlining the feature on the SeasonalBot repo, we'll get it approved so you can start working on it.

**Comment by RohanRadia** [comment]
Thanks Scrag. Will make it now.

**Comment by sco1** [comment]
A PR for this feature has been created: https://github.com/python-discord/seasonalbot/pull/212
