### ISSUE TITLE
Suggested addition to Docker "Possible Issues" section of site

### ISSUE THREAD

**Issue by bendiller** [python-discord/meta#33]
I'd like to recommend a "possible issue" to add to the site at https://pythondiscord.com/pages/contributing/docker/#possible-issues. Windows users who are new to Docker and just getting it running for the first time will likely encounter an error when trying to use the `docker-compose up` command. 

This error is caused by drive sharing not being configured in Docker's settings, and the error output will be something like: `ERROR: for bot_bot_1  Cannot create container for service bot: b'Drive has not been shared'`.

If this suggestion is approved, I'd like to attempt to implement it. I'll be happy to provide instructions on configuring drive sharing, including screenshots, etc.

Thanks!

**Comment by scragly** [comment]
Sounds great, thanks.

The contributing pages are within a wiki platform on the website and are currently editable by admins only. If you wanted to write up something, including any screenshots, you're more than welcome to do so as a comment here for it to be added by someone with site admin access. 

It would also allow for a chance for any feedback this way before adding any new content.

Thanks again for the information!

**Comment by bendiller** [comment]
### Drive has not been shared (Windows users)

When attempting to run the `docker-compose up` command, on a Windows machine the user may receive the following or similar error message:
`ERROR: for bot_bot_1 Cannot create container for service bot: b'Drive has not been shared'`

**Problem**
Windows has not been configured to share drives with Docker.

**Solution**
NOTE: Solution requires Windows user credentials for an account that has administrative privileges.

1. Right-click the Docker icon in the Windows system tray, and choose "Settings" from the context menu.
![PyDiscScreenShot1](https://user-images.githubusercontent.com/17148102/65978759-7e007380-e431-11e9-8e27-7f1408d216f9.png)

2. Click the "Shared Drives" label at the left, and check the box next to the drive letter where your project is stored.
![PyDiscScreenShot2](https://user-images.githubusercontent.com/17148102/65979221-29112d00-e432-11e9-9e65-bbca5a6a3d95.png)

3. Click "Apply" and enter appropriate Windows credentials (likely just your own account, if you have administrative privileges).

4. Re-run the `docker-compose up` command.

**Comment by bendiller** [comment]
That's a draft of what I'd suggest adding. Feel free to modify it however you all like, of course, and if you need me to make any changes myself, I'd be happy to.

Thanks!

**Comment by MarkKoz** [comment]
This has now been added. However, due to uploading of images on the wiki being broken currently, the page still uses the images hosted on GitHub.
