### ISSUE TITLE
Resource suggestion: SoloLearn

### ISSUE THREAD

**Issue by eunicode** [python-discord/meta#40]
I'd like to recommend adding SoloLearn's Python 3 course to the _Interactive Learning_ list. 
https://www.sololearn.com/Course/Python/

It has exercises and quizzes and is similar to codecademy, except it's free. It also has a free mobile app so people can learn on their phones.

It covers 

- basic concepts, 
- control structures, 
- functions and modules, 
- exceptions and files, 
- types, 
- functional programming, 
- object-oriented programming, 
- regular expressions 
- and pythonicness and packaging

**Comment by scragly** [comment]
Hi eunicode, thanks for the suggestion!

We had a talk about it in `#dev-contrib` for a bit and it appears we don't have much issues with adding it in as a resource. 

You should be able to see this resource popping up in the short term on our resources page.

Thanks again!
