### ISSUE TITLE
Topical FAQs

### ISSUE THREAD

**Issue by dinosawrusrex** [python-discord/meta#43]
Just wanted to field some thoughts about topical frequently asked questions. Two options I thought where this page could exist:

1. A new page on Python Discord's homepage.
2. A new section in the Resources page.

For context, I was recently asked the "Flask or Django, which should I use?" question, and I recall seeing this already asked on other general help channels multiple times. I thought it would be great if questions like that had a page we can point people to that:

- has Python Discord's take on this question
- Includes some considerations
- Links resources or external sites that try to already answer these questions

The current FAQ page is quite general which is great for someone just starting. Extending this FAQ format would work, and having it on a new page would not crowd the existing FAQ.

The resources page could be a suitable candidate to add a section to, and I can see it fitting the style and context of existing resources!

**Comment by MarkKoz** [comment]
Something like this has briefly been discussed internally before. I think it's a good idea to have some longer guides written and put up on our website. That could be something generic like the example you used or solving some specific issue (I have a couple ideas for ones we encountered while developing our projects). My idea was for a separate wiki category that has pages for different guides. There was talk of moving some of the longer tags over to the website too.

**Comment by jb3** [comment]
I think this fits well into our guides system which our helpers can add content to. We're also open to taking community suggestions. Right now this would be a user sending us a GitHub Markdown gist or the like and we will add it to our repository, but in future we are putting guides right in our site repo, so users can add content directly to the live site.

You can see all our current guides at https://pythondiscord.com/pages/resources/guides/
