### ISSUE TITLE
External API Topical Help

### ISSUE THREAD

**Issue by dinosawrusrex** [python-discord/meta#44]
I see some questions about external APIs somewhat regularly. It somewhat falls into the Web Development category, but I think perhaps a separate topic might be more appropriate?

**Comment by jb3** [comment]
I think this is discussion which fits fine into web development, and if it is getting too prevalent there then I think this is suitable in the help channel system. By far our most requested external API is discord.py, and other less notorious APIs fit well and receive help in the regular help system.
