### ISSUE TITLE
Add Think Python to literary resources

### ISSUE THREAD

**Issue by ghost** [python-discord/meta#45]
For inclusion on the resource page I would like to suggest the book "Think Python" by Allen B. Downey. It has a free license so you can download & contribute or buy the book. It has a stronger taste of informatics than other beginner books, which is a good thing in my opinion, because the more experienced and smart ones don't get bored so quickly. Due to the good structure of the content, the book is still accessible to beginners easily.

**Comment by sco1** [comment]
Thanks, we will take a look.

**Comment by sco1** [comment]
Do not vandalize issues.

**Comment by PaddyEff** [comment]
So I need to ring the big alarm, only to remove an issue that I want deleted?

**Comment by sco1** [comment]
Unless the reason for "ringing the big alarm" is that you suddenly don't think this text is appropriate for adding to our resources, there's no reason for you to touch it at all.

Throwing a tantrum isn't an appropriate reason, and continuing to abuse our repositories will result in your removal.

**Comment by PaddyEff** [comment]
Too funny, really. I DO NOT WANT TO BE ACCOCIATED with any of you guys. It's thats easy.

**Comment by lemonsaurus** [comment]
After discussing this in our staff meeting, we have decided that this will be added to our resources.
