### ISSUE TITLE
Enable reactions for #python-language

### ISSUE THREAD

**Issue by makusu2** [python-discord/meta#46]
There seems to be a fear that allowing reactions could allow users to discreetly disturb others, or meaning a great deal of extra work for the moderation team. It makes sense that reactions are not allowed on very active channels. However, could we enable reactions for #python-language? 

I doubt the new #python-language channel will be used as frequently as the really active channels like the help channels, so just like with #careers and #meta, helpers/mods/admins would quickly notice if someone is abusing reactions, so it shouldn't be a nightmare to deal with like it would be in a help channel.

**Comment by Akarys42** [comment]
I agree, it seems like the channel is calm and moderated enough to have reactions enabled.

**Comment by wookie184** [comment]
Especially when the PR for https://github.com/python-discord/bot/issues/915 (forbidding reactions when a channel has been shhed) has been merged, I also think it would be nice to at least try out enabling reactions in python-language.

**Comment by jb3** [comment]
Let's give it a go, permission enabled. We'll assess how this has gone in a couple of weeks.
