### ISSUE TITLE
Align list in #how-to-get-help message for compact mode

### ISSUE THREAD

**Issue by Numerlor** [python-discord/meta#47]
With the compact mode enabled, the starting line continues inline after the nick, making the first item in the message's list enabled.
This can be solved by adding some whitespace like the zero width space (U+200b) and a newline after it, however it will also add an empty line when viewed using the cozy mode
| ![compact](https://i.imgur.com/6VMzNi5.png) | ![cozy](https://i.imgur.com/MmcF9SM.png) |
| - | - |

**Comment by fadedmax** [comment]
YES! please make this happen, i dont care what you have to do, but as a compact mode user for over 2 years, a discord user for over 4, this would be so much better for us compact mode people.

**Comment by SebastiaanZ** [comment]
The vast majority of our users use "cozy"-mode, though. Making this change would make the formatting worse for the majority of users, while the current situation is completely in line with how "cozy"-mode always works.

**Comment by hedythedev** [comment]
How about displaying the whole how-to-get-help message as an embed? That might make it look consistent on different modes

**Comment by fadedmax** [comment]
@hedythedev Even better.

**Comment by fadedmax** [comment]
I think putting this in a embed would be the best solution @SebastiaanZ

**Comment by jb3** [comment]
I'm not sure I agree. Having seen some users experiencing issues with embeds recently I'm less thrilled about the idea of putting important content inside them.

The way Discord's appearance settings choose to display embeds is odd, the "embed links when pasted in chat" option disables embeds which many users are not aware of..

**Comment by SebastiaanZ** [comment]
I don't like embeds here either. The support for embeds cross-platform is not unified, meaning that embeds are displayed differently on different platforms and that updates to embed rendering hit platforms at different times, often breaking something one one platform only. That's not a good situation to have for important information.

Moreover, as @jb3 mentions, some users have embeds disabled, leading to the information not being visible for them at all.

I think the question boils down to weighing making the message rending slightly worse for a lot of users or slightly better for fewer users (despite the current rendering just being the default for the viewing mode they've chosen).

**Comment by SebastiaanZ** [comment]
I've added this to the new version in how-to-get-help. I haven't heard complaints about the empty line in cozy mode yet, so I guess it's all good.

**Comment by fadedmax** [comment]
Know this issue is closed, but this appears to have been de-fixed in march 2021. A bit late but nontheless
<img width="911" alt="image" src="https://user-images.githubusercontent.com/32599075/173902402-9462d5be-edcc-4100-8ef4-28f5c8c1a343.png">
