### ISSUE TITLE
Add EduBlocks to list of Tools/IDE's

### ISSUE THREAD

**Issue by JoshuaLowe1002** [python-discord/meta#48]
Hiya,

I create https://edublocks.org which is a popular program for beginners/young people to learn Python through blocks.

It might be something you'd like to add to your list on the website!

**Comment by j03b** [comment]
Hey Joshua! Thanks for opening this. We've had a play around with your application and found it awesome!

We've added it to the [interactive section](https://pythondiscord.com/pages/resources/interactive/) of our resources document.
