### ISSUE TITLE
Resource for questions of different Python experience levels

### ISSUE THREAD

**Issue by Anubhav1603** [python-discord/meta#49]
If we have questions for beginner,intermediate and advance level programmers in our resource page then it will be great.

**Comment by wookie184** [comment]
I'm not really sure writing questions like this ourselves would be worth it, it would take a lot of time that could be better spent elsewhere, and there are already plenty of websites out there that do a similar thing much better than we could, e.g. Codewars, Leetcode, HackerRank, ect. I don't think we list these websites on our website currently, maybe that would be a better idea than writing our own questions, possibly a `practice` section on [this page](https://pythondiscord.com/pages/resources/interactive/)?. What are other people's thoughts on this?

**Comment by Anubhav1603** [comment]
Yeh I like this idea

**Comment by jb3** [comment]
I'm not even sure we need to add a practice section.

The existing tools on the page wookie has could probably have some sort of difficulty tag added to them. For example, CodeCombat is relatively beginner friendly meanwhile exercism has more difficult questions.

Maybe we could add some more resources like proposed and just tag each one with the difficulty level.

**Comment by Akarys42** [comment]
I think it would be really nice to tag (newer and older) resources with an experience level tag as for now, except for some description, we don’t say what is oriented to which level.

**Comment by jb3** [comment]
After the staff meeting on 11th October, we've decided that we should extend this to our entire resources collection. We need to decide how we want to present difficulty visually but this can be considered actionable by any Helper — just speak to other in #organisation to discuss our approach to it.

**Comment by jb3** [comment]
Superseded by python-discord/site#449.
