### ISSUE TITLE
Add Jetbrain's academy to python reasources

### ISSUE THREAD

**Issue by ChillFish8** [python-discord/meta#53]
After having a brief play around with JB's academy system built into their IDEs like PyCharm it's quite the awesome set of tutorials with interactive lessons straight in the IDE along with getting users used to the PyCharm system and think it would be something that any beginner could find helpful to get to grips with Python.

**Comment by wookie184** [comment]
Thanks for the suggestion, it looks like a great resource. Have added it to the website on [this page](https://pythondiscord.com/pages/resources/interactive/) :+1:
