### ISSUE TITLE
New OT Channel: Special programming language channel

### ISSUE THREAD

**Issue by ks129** [python-discord/meta#55]
I know other languages channels have been declined multiple times, but I have one concept that may work: 4th OT channel, prefixed with `lang-` and then programming language. This language should change every day and during one language session, only talking about this language is allowed. This shouldn't just these big, most used languages, but smallers too. This will help peoples exploring more languages about what they maybe never knew before. Every time when language change, bot should send message to channel that contains short information about language, logo and hello world example.

**Comment by Akarys42** [comment]
I do think an off-topic other language channel would work, but I’m not sure about this one. I think this can be a good concept, although it doesn’t seem to fit the context of PyDis. If we had an other channel language, it would be about random thoughts and helping on various language, while this proposal would make us focus the discussion on a particular language, that most people would probably don’t know. I’m sorry, but I don’t think this is a good idea, at least for this server.

**Comment by ks129** [comment]
I don't think so @Akarys42 . I think this should be good feature to help finding and learning new languages. This should be able to store Discord invites to server when this language have official server and with `!invite` command, bot should print out current language server. Random thoughts (and maybe some help too) may be in default OT, but this channel should be more for getting started with new languages.

**Comment by Akarys42** [comment]
This doesn't fit PyDis in my opinion, people don't come here to learn new languages, they just want to learn python.

**Comment by lemonsaurus** [comment]
We discussed this in the staff meeting on the 11th of October, 2020.

The staff feels that this would have poor user experience - members would find a channel about their favorite non-Python programming language, and the very next day the channel would be gone. We expect a lot of people would be upset by this.

We also don't really see the value of earmarking a single off-topic channel for programming discussions. In a way, _all_ our off-topic channels are already channels in which you can discuss other programming languages. 

Overall, we're not interested in doing this, at least not at this time.
