### ISSUE TITLE
Book suggestion for "Resources" page

### ISSUE THREAD

**Issue by PythonTryHard** [python-discord/meta#57]
Zig (moderator) directed me here from `#meta` channel

I found two books on Python 3 from Springer's COVID-19 "giveaway", [compressed and uploaded off-site in good faith](https://www61.zippyshare.com/v/8aJMHi59/file.html) due to GitHub's 10MB attachment constraint. I took a look at the books and to me they feel like they can be of good use to people.

**Comment by mbaruh** [comment]
Could you provide an official link to this resource?

**Comment by PythonTryHard** [comment]
[The giveaway expired on July 1, 2020](https://www.springernature.com/gp/librarians/the-link/blog/blogposts-ebooks/free-access-to-a-range-of-essential-textbooks/17855960), sadly. The official link for the books are as followed:
- Beginner: https://link.springer.com/book/10.1007/978-3-030-20290-3 (32.09 EUR)
- Advanced: https://link.springer.com/book/10.1007/978-3-030-25943-3 (46.00 EUR)

**Comment by gustavwilliam** [comment]
If the giveaway is over, it sounds like we wouldn’t have permission to redistribute the PDFs. I assume their policy mentions that somewhere.

**Comment by PythonTryHard** [comment]
I sent Springer an email regarding this issue. Until a response is received I'll close this issue, and send an update according to their verdict at a later date.

**Comment by PythonTryHard** [comment]
Springer got back to me, saying what basically boiled down to "No, no redistributing. If you want, link to purchase page". This one staying closed.

**Comment by MarkKoz** [comment]
The resources page isn't limited to free resources. These could still be considered for addition as paid resources, but it's harder to review them since they have to be bought.
