### ISSUE TITLE
Create new help voice channel when other/others are full

### ISSUE THREAD

**Issue by mcurranseijo** [python-discord/meta#59]
Recentely in #meta a user mentioned needing voice help but the voice channel was full. This gave me the idea of having the voice help channels be generated when one is full. These could be placed in one category of channels and have the bot be checking number of users in each channel above the main one, If this is something that could be worthwhile I'd love to attempt it and hear what others suggestions were for this.

**Comment by jb3** [comment]
I don't think we see enough voice traffic to warrant such a dynamic system right now, and it would be infinitely more difficult to moderate.

As a response to this though I have split the channel in two and made a new 5 member capped voice channel for code help, we'll see if this resolves it. This should still be easy to moderate while allowing for people to get voice help.

I'd like to remind users now though that our main functionality as a Discord server is to operate our text chats and voice is an additional feature, we may look in future about gating voice access to prevent from spammers which may let us be more relaxed with voice permissions.
