### ISSUE TITLE
Update the contributing guides 

### ISSUE THREAD

**Issue by Numerlor** [python-discord/meta#60]
On windows, docker is now handled through docker desktop which already comes with compose installed making the docker compose requirement for the projects extraneous on the platform.

In <https://pythondiscord.com/pages/contributing/hosts-file/>, the guide refers windows users to use the `docker-machine ip defualt` command, which is no longer available with docker desktop. 
The IP used by docker is stored in the hosts file which needs to be edited anyway so the guide can direct there for it.  Or the IP is already pointed at by `host.docker.internal` in the hosts file which could also be added to the site's allowed hosts and used instead of the `pythondiscord.local` domain name. This will also keep everything working in case docker decides to change it. The docker domain name is not available on linux https://github.com/docker/for-linux/issues/264

The mac docker environment also seems to have been changed but I don't have a way of looking at that

**Comment by Akarys42** [comment]
Alright, I'll take a good look at the contributing guides when [`server-bootstrap`](https://git.pydis.com/server-bootstrap) will be ready. In the meantime, feel free to report us everything you think is missing on those guides.

**Comment by spitfire-hash** [comment]
I tried to run docker with my 5 years old 4GB RAM computer, but it just didn't worked, it was too heavy for computer, the sound of fan just maximized, so I needed to stop it. So you may include something like this to contributing guides with docker
```markdown
If your computer's RAM is not enough for running multiple containers at the same time, do not try to run them.
The computer might crash or can be really slow, so try to do it with traditional way.
```

**Comment by hedythedev** [comment]
**Add example `.env` file to seasonal bot guide**
The guide for python bot has [the example `.env`](https://pythondiscord.com/pages/contributing/bot/#environment-variables) with all the keys with example values in it, which is useful, because one can just copy/paste and replace the values, but in the [seasonal-bot development environment section](https://pythondiscord.com/pages/contributing/seasonalbot/#development-environment), there's no example `.env` and one would have to copy each of the keys and the `=` manually.

**Comment by spitfire-hash** [comment]
**Improve hosts file guide**
In the [configuring the hosts file](https://pythondiscord.com/pages/contributing/hosts-file/) guide, add that you need to install `docker-machine` separately from `docker-desktop` i.e. the `docker-desktop` does not include `docker-machine`. The `docker-machine` is needed for [knowing host ip in Mac and Windows](https://pythondiscord.com/pages/contributing/hosts-file/#windows-macos). You can add requirements to [here](https://pythondiscord.com/pages/contributing/bot/#using-docker)

**Comment by Numerlor** [comment]
Information about the redis setup should be added to the bot guide

**Comment by RohanJnr** [comment]
https://pythondiscord.com/pages/contributing/sir-lancebot/#development-environment
We should also include USE_FAKEREDIS in the additional env variables section of @sir-lancebot
As sometimes, we won't be running the project with docker(if we want to use a debugger, etc).

**Comment by RohanJnr** [comment]
https://pythondiscord.com/pages/contributing/sir-lancebot/#development-environment
Can we have a copy-paste format for the env variables on Lancebot contribution guide

Example: https://pythondiscord.com/pages/contributing/bot/#environment-variables
![image](https://user-images.githubusercontent.com/37217450/99981946-f8c3e500-2dcf-11eb-9194-fc65163e35d9.png)

**Comment by Akarys42** [comment]
Let’s gather all the default URLs for a working docker setup, here is what we have so far:

* `urls.snekbox_eval_api`: `http://snekbox:8060/eval`

Feel free to edit if you have more!

**Comment by sebkuip** [comment]
As per Akarys request to make a comment:
Add to the guidelines on exactly how a document should be formatted. Right now they only state "run pre-commit", which can return "passed" or "failed". With no pointers to either the erroring line or the correct formatting, it can be very frustrating to fix the failed pre-commit.

**Comment by Inheritanc-e** [comment]
We would also need to include adding `fake_redis=true` in the contributing guide, as it errors out without it.

**Comment by jb3** [comment]
Most of the feedback here has been addressed where we thought it was appropriate, with simplifications in a lot of places.

I'll close this now but feel free to drop notes on Discord or another issue if anyone has further feedback regarding contribution guides.
