### ISSUE TITLE
Repl.it and Google Collab for the interactive resources page

### ISSUE THREAD

**Issue by jsalsman** [python-discord/meta#61]
I propose adding https://repl.it/ and https://colab.research.google.com/ to https://pythondiscord.com/pages/resources/interactive/ because they both have featues, capabilities, and use cases unlike any of the other resources currently listed. Repl.it allows web IDE for production Flask servers, X Window system and other graphical output, and although their docker images lack e.g. ffmpeg for constructing animations from matplotlib, they are constantly moving in the direction of such additional capabilities. Google Collab is a free-as-in-beer high-powered custom version of Jupyter Notebook which supports e.g. !apt-get to install arbitrary Debian packages to the runtime, which is very generous with CPU and memory, and well-integrated with Google Drive. 

I would submit a pull request for markup, but I can't find the current version of the site. https://github.com/python-discord/site/tree/master/pydis_site/apps/home/resources/interactive_learning_tools is more than a year out of date and doesn't reflect the current content. Where are the pythondiscord.com/pages/resources/interactive source files?

**Comment by gustavwilliam** [comment]
I don't quite see how [repl.it](https://repl.it/) would fit in the interactive resources category. However, it's a great tool, which is already listed on our [tools](https://pythondiscord.com/pages/resources/tools/) page. From what I'm aware, the interactive resources page is more focused on learning resources.

The articles are edited by staff members and I believe they're simply part of a database. In other words, you are completely right in proposing it here and there's no need to open a PR.

**Comment by jb3** [comment]
As @gustavwilliam mentions, we do already list repl.it in our tools section.

I think Colab is a fantastic tool — and definitely one we should be listing. I'm not sure which section it should go under, it certainly comes off as more of a tool than a learning resource (even though it can be one — this isn't the sole purpose).

I'll mark this as actionable for now but would love to hear from others about where it should go.

**Comment by jsalsman** [comment]
I wonder whether some sites like repl.it qualify under both instructional and tools categories?

**Comment by jsalsman** [comment]
@gustavwilliam @jb3 how do you feel about python-first hosting providers like https://pythonanywhere.com ? They have a decent free tier, and have had good support for many years, but I wonder how they compare to Heroku and the like these days.

**Comment by janine9vn** [comment]
Google Collab has been added under our "Tools" page since it fits best within there. We've decided to keep repl.it under the tools category for the time being.
