### ISSUE TITLE
Resource Recommendation: Mathematics for Machine Learning

### ISSUE THREAD

**Issue by scragly** [python-discord/meta#62]
Relaying a resource recommendation given by GamerLegion#0987 in our #meta channel:

> guys i found a public book by cambridge (no copyright issues its publically avalable)
> 
> its a maths book for ML and CSE 
> 
> https://mml-book.github.io/
> 
> could you add this to #resources please

Please leave comments/reviews about the recommended addition in this ticket, thanks!

**Comment by wookie184** [comment]
Looks like a great book, but it isn't really Python related so I think it would be a bit out of place on our resources page. I don't think it would be that relevant/useful for most people looking at the page. That's just my thoughts though, would be interested to hear what others think.

**Comment by janine9vn** [comment]
While this wasn't Python related enough to include on our resources page, it was voted on to be pinned in our #data-science topical channel. You can find it there now.
