### ISSUE TITLE
Resource page addition for Python gotchas(?)

### ISSUE THREAD

**Issue by PythonTryHard** [python-discord/meta#63]
https://github.com/satwikkansal/wtfpython has been on GitHub trending recently. From a glance and some initial reading it seems suitable (at least to me) for the Resources page. What's your opinion?

**Comment by wookie184** [comment]
Nice, that repo is pretty interesting, enjoyed reading through it. I think it would be quite nice to have somewhere on the site. Not exactly sure where would be best though, probably the guides section on [this](https://pythondiscord.com/pages/resources/reading/) page?

**Comment by PythonTryHard** [comment]
Seems reasonable to me, since the repo can be considered as guidance to prevent confusing bugs although I would like to have some more opinions on the matter

**Comment by 15695** [comment]
I also agree that this would be nice to have and also think that this should be in the Reading section like @wookie184 mentioned.

**Comment by janine9vn** [comment]
This was voted to be added to our Resources page. You can find it under Reading -> Guides.
