### ISSUE TITLE
Disabling image send perms for new users in python-general

### ISSUE THREAD

**Issue by wookie184** [python-discord/meta#64]
It was recently brought up in meta that there have recently been some incidents of new users joining and spamming inappropriate images/videos, we're able to respond to these incidents pretty quickly but it can still be quite disturbing for the people who see the images. A proposal was made to disable image/video send perms for new users (maybe users who have only joined the server in the last 2 days, could also depend on messages sent) in the hope it would reduce this problem. 

From my understanding this would require a new role to be created, which isn't ideal. Another problem is that images could still be sent in embed links, so for this to be effective those permissions may also have to be disabled as well. I don't think not being able to send images should be a massive problem as sending code would be better in a pastebin or codeblock anyway. As well as this, these problems would also only affect the minority of users. It would probably also only really need to apply to high traffic channels such as python-general.

Of course this also wouldn't be perfect, not all accounts may be new if they had been hijacked etc. I think it could still make a difference, but I'm not sure whether the positives outweigh the negatives. Would be interested to hear any thoughts/opinions.

**Comment by gustavwilliam** [comment]
As expressed in #meta, I like the general idea of disabling it for new users, but I don’t think it would be a good idea to disable the permission for everyone.

I often find myself in conversations where the other user is showing what they’ve built, through both videos and images. There are also cases where you may be showing your editor layout or formatting of the python code. In short, I think it would make sense to let most people have the permissions.

However, we could draw a parallel to the streaming permissions in VC. That works fine, though isn’t really optimal when helping out in VC (thanks, admins who make that possible at times!). The most restrictive solution should still let contributors and all of staff send images in #python-general. They’ve all proven to be trustworthy and won’t abuse this.

If we do add a separate role for members with image permissions, I think it would be nice it to merge it with the Voice Verified role as well. That would be like a “you’re not just a basic troll” role, which the Voice Verified role basically is already. This could potentially be a role used for other gatings as well. If we want to restrict other permissions to only allow certain, slightly more trusted, people, it would be easy with this role.

**Comment by wookie184** [comment]
This has now been done, it was discussed in a staff meeting and it was decided to restrict attachment and embed sending permissions for all users for now. There is an issue on the bot repo to allow users with a certain level of activity to gain these permissions back, but it is still being discussed, see https://github.com/python-discord/bot/issues/1258.
