### ISSUE TITLE
Adding Python Crash Course to the resource list.

### ISSUE THREAD

**Issue by Inheritanc-e** [python-discord/meta#65]
I suggest adding the book Python Crash Course to the resources page as it teaches beginners the basics of the language with interactive activities for each chapter. It has various projects such as games, data visualization , and web building. It teaches us to build a simple alien invader game through pygame. It teaches about data visualization through matplotlib, at last but not least it teaches us about we building and hosting a web application. Which is a significant skill to have as a programmer.

**Comment by janine9vn** [comment]
This has been voted to be included on our resources list. You can find it there now under the "Read" section. Thanks!
