### ISSUE TITLE
Finding fresh help channels

### ISSUE THREAD

**Issue by shreyassranganatha** [python-discord/meta#66]
It takes work to find an active help channel that nobody's already begun helping at. I suggest a sorting mechanism to have the help channels consisting of ONLY the claimer's questions be sorted at the top of the OCCUPIED help category, and it descends to channels with larger answer streams; or better, a whole new category for the free (questioned but unanswered yet) help channels

**Comment by gustavwilliam** [comment]
I have not thought through it this *would* be a good idea or not. However, it’s not quite plausible, considering the rate limits for moving channels set by discord. Resorting them this often would probably not even be possible in some cases.

Adding such a category would also increase the complexity of the system quite a bit, which isn’t something we should do unless it provides significant improvements. I don’t think this falls under that category.

**Comment by shreyassranganatha** [comment]
Fair @gustavwilliam, but having a distinction between at least the fresh ones (unanswered but questioned) and the being answered ones should add a great amount of simplicity in finding channels to help from around 20 occupied channels that are usually there

**Comment by gustavwilliam** [comment]
Maybe it would be nice for finding channels where no person had written anything, but it would also mean that someone asking the person to clarify without knowing the answer would move it to that category of "being answered", which would probably get very little traction.

Either way, discussing the value of this feature doesn't serve much use, considering Discord's rate limits.
