### ISSUE TITLE
Ubuntu codenames for help channel names

### ISSUE THREAD

**Issue by ks129** [python-discord/meta#67]
Currently help system use elements for channel names, but we should have alternative pools for names. I think one of these pools should be Ubuntu version codenames, like `groovy-gorilla` (so `help-groovy-gorilla`). I think this may be even easier to remember than elements.

**Comment by Abhigya123** [comment]
If the main point is to remember the channel name why not create a command which shows the help channels that the user has claimed?

**Comment by ks129** [comment]
@Abhigya123 Not only remembering, elements should stay too. Bot should like use new pool every month/week.

**Comment by mbaruh** [comment]
How would you implement such a feature?

There isn't a point in time in which channels are safe to tinker with outside the system, name changes are pretty heavily rate limited, and we don't want to overcomplicate the system.

I'm also considering how difficult it would make for users to later find a conversation they had if the channel names keep changing.

**Comment by ks129** [comment]
@mbaruh This should change channel name when this move to available, not update everything at once. When this get ratelimited, then this should try renaming it again when moving to available next time. Maybe to make this little bit easier to find old discussions, there should command that show last name of mentioned channel. Last name should be stored to Redis, as this is not really important data.

**Comment by SebastiaanZ** [comment]
I'd implement it by changing the channel name when it goes into the available category. Such a single name change would be well within rate limits and the name then wouldn't change between asking a question and waiting for an answer. Alternatively, it could be renamed when it's moved to dormant, but that comes with the price of making it more difficult to find the channel you just got help in within the dormant category.

**Comment by mbaruh** [comment]
Yeah, that's more or less what I considered as well, though making the change as it moves to available sounds better for the reason stated above.

Still, I'm worried about the effect it would have as we have users who find the system confusing already.

**Comment by ks129** [comment]
@mbaruh I think as these names will not change so fast and when some users can't find their help session, then they can ask help for it. When names change once per month, then users have time to search for this and I don't think much users need 1 month+ old help sessions.

**Comment by Akarys42** [comment]
Changing when the channel goes to the available category seems like the best idea.

I am not sure about using the Ubuntu codenames though, we aren't an Ubuntu community, some people could ask why we didn't take the codenames of X or Y distro, and we wouldn't really have a good justification.

**Comment by mbaruh** [comment]
A month's time is the maximum, for other users it will be less than a month, and there will always be a user for whom the name will change shortly after they closed the channel.

And yeah, I'm not sure if once a month is long enough.

**Comment by SebastiaanZ** [comment]
I doubt people find an older help channel they were active in by the name of the channel. Channels move relatively quickly through the system, making the scroll up the channel history become bothersome quickly. I don't really think that other than the "I just closed the channel, I still know the name, let's look it up" looking up channels by name for their more distant history happens a lot.

Channel mentions will automatically adapt and the Discord search feature will also have no issue with a channel that changed names.

I don't think the name changing in itself, if we do it at the right time in the channel's life cycle, is too much of an issue, especially not given that we won't do it all that often.

**Comment by ks129** [comment]
@Akarys42 I think having name pools that is not related with Python language is good, because when name is related with Python, users may take that this channel is related with it's name.

**Comment by jb3** [comment]
I think I agree that Ubunutu is not the direction to go here. Some existing proposals were famous computer scientists (Lovelace, Babbage, etc.) or Monty Python sketches. I think we can keep it more relevant without causing confusion about the topic.

**Comment by SebastiaanZ** [comment]
Let's consider one of the other, broader categories of names for a potential additional name pool.
