### ISSUE TITLE
Python family snakes latin names for help channel name

### ISSUE THREAD

**Issue by ks129** [python-discord/meta#68]
Another idea for pool of help channel names: Pythonidae (Pythons) Latin names.

Here is pool that I collected:
1. an-childreni
2. an-maculosa
3. an-perthensis
4. an-stimsoni
5. ap-papuana
6. as-melanocephalus
7. as-ramsayi
8. bo-albertisii
9. bo-biakensis
10. bo-boa
11. bo-fredparkeri
12. bo-huonensis
13. bo-meridionalis
14. bo-montanus
15. li-fuscus
16. li-mackloti
17. li-olivaceus
18. ma-reticulatus
19. ma-timoriensis
20. py-molurus
21. py-sebae
22. py-regius
23. py-bivittatus
24. py-curtus
25. py-breitensteini
26. py-anchietae
27. py-brongersmai
28. py-kyaiktiyo
29. py-europaeus
30. mo-amethistina
31. mo-bredli
32. mo-azurea
33. mo-carinata
34. mo-oenpelliensis
35. mo-spilota
36. mo-viridis
37. mo-riversleighensis
38. si-boeleni
39. si-clastolepis
40. si-kinghorni
41. si-nauta
42. si-oenpelliensis
43. si-tracyae

Prefixes is short versions of generas because writing full version will not look good in mobile. Used Wikipedia to create this list. Not all Pythonidae names is included here and it's possible to extend this list in future.

**Comment by Akarys42** [comment]
That’s a cool idea, although maybe without the prefix, it could be pretty noisy with the `help-` prefix. Either way, I like this!

**Comment by ks129** [comment]
No problem, I can extend it I think up to 40 names. Removing prefix will make names incorrect, as Latin names is like: `Morelia bredli`and I just made first part shorter.

**Comment by ks129** [comment]
Extended list, but left some really similar names out.

**Comment by swfarnsworth** [comment]
I really like Latin, but names of elements are more familiar than the names of species. I think people are going to look at the Latin names, glaze over, and have trouble remembering which help channel is which. For example, I don't think anyone is going to read `mo-riversleighensis` and have an idea of what that sounds like.

**Comment by ks129** [comment]
@swfarnsworth We discussed about prefixes in #meta and decided to leave them out. I also left out similar names and as they are pretty different, user should be able to remember enough of channel name to identify.

**Comment by SebastiaanZ** [comment]
The general consensus in the staff meeting was that these names would not be more memorable than the names we currently. However, not everyone is happy with the memorability of the current names as well, but we don't have a solid consensus for an alternative set of names at the moment. This is something we need to think about before rushing in an alternative.

**Comment by jb3** [comment]
We've got a plan for this internally which we'll be converting into issues on the necessary repositories in the coming months.
