### ISSUE TITLE
Add A Wedge of Django: Covers Python 3.8 and Django 3.x to the resource list

### ISSUE THREAD

**Issue by eivl** [python-discord/meta#69]
![](https://cdn.shopify.com/s/files/1/0304/6901/products/AWoD-Front-5.5x8.5in_1024x1024@2x.jpg?v=1600471198)

This book has previously been called Django Crash Course. It's written by Daniel & Audrey Feldroy (same authors as Two scoops of Django).

The book is excellent for anyone beginning with Django, it's a perfect springboard before you go over to two scoops of Django. 
It's really a tutorial on how to get started with Django, a very suited book for our users. It's up for pre-order right now, I got an early preview of the book and I enjoyed how simple and natural it is written.

**Comment by janine9vn** [comment]
This was voted to be added to our resources at Sunday's staff meeting. You can now find it on our resources page!
