### ISSUE TITLE
Add Neural Networks from Scratch to the resource list

### ISSUE THREAD

**Issue by eivl** [python-discord/meta#70]
I suggest we add this book/ebook to the resource list. It's a great resource for anyone wanting to understand Neural Networks before they go deeper into ML and Deep Learning.
It's also in my opinion a way to figure out if you like the topic before you sink 6months - 2 years into learning it. 

https://nnfs.io

![](https://nnfs.io/static/images/neural-networks-from-scratch-main-dark.png)

**Comment by janine9vn** [comment]
This was voted to be added at our staff meeting. You can now find it on our resources page.
