### ISSUE TITLE
Resource recommendation: Inferential Thinking (free data-science book)

### ISSUE THREAD

**Issue by lxnn** [python-discord/meta#72]
I recommend the book _Inferential Thinking_ by Ani Adhikari and John DeNero. Not only is it a solid introduction to data science, it teaches you Python as you go.

It was written as the textbook for UC Berkeley's undergraduate introductory data science course. It is freely available at: [www.inferentialthinking.com](https://www.inferentialthinking.com)

**Comment by jb3** [comment]
This has been added to our resources page under the [books section](https://pythondiscord.com/pages/resources/reading/#books) of our reading page.
