### ISSUE TITLE
Resource and/or tag recommendation: guide to floating point numbers.

### ISSUE THREAD

**Issue by lxnn** [python-discord/meta#73]
I think this website would be a useful place to point people who are confused by the results they get when they compare floating point numbers in their code: [https://floating-point-gui.de](https://floating-point-gui.de)

I propose we introduce a tag for this. Something along the lines of:

> Some fractional numbers cannot be represented exactly as binary floating point numbers.  So when comparing floating point numbers it's usually best to include a margin of error: test that they are similar rather than exactly equal.
> 
> Instead of:
> ```python
> if x == y:
>     ...
> ```
> Try:
> ```python
> if abs(x - y) < epsilon:
>     ...
> ```
> Where `epsilon` is a small number.
> 
> See this website for more information: [floating-point-guide.de](https://floating-point-gui.de)

**Comment by lxnn** [comment]
Remembered that there's also `math.isclose`.

**Comment by laundmo** [comment]
in staff meeting the `fractions` and `decimal` libraries were also mentioned as possible things that should be mentioned in the tag

**Comment by lxnn** [comment]
Correct link is [https://floating-point-gui.de](https://floating-point-gui.de)

**Comment by jb3** [comment]
This is added in python-discord/bot#1395
