### ISSUE TITLE
Resource recommendation: Khan Academy algorithms course

### ISSUE THREAD

**Issue by lxnn** [python-discord/meta#74]
Khan Academy's algorithms course provides a good first introduction to algorithms at a level that I think would be suitable for many of our users.

https://www.khanacademy.org/computing/computer-science/algorithms

The only caveat is that the programming exercises use Javascript rather than Python.

**Comment by jb3** [comment]
We discussed this in the staff meeting and decided against it, the main reason being that as a Python community it's best for us to stick to recommending the best Python resources — we can't let it slip into generic computer science as our list sizes would explode.
