### ISSUE TITLE
Suggestion: make the person who claimed the channel more distinguishable. 

### ISSUE THREAD

**Issue by kinguardo** [python-discord/meta#75]
Few suggestions:
1. Instead of adding the name of a person who claimed the channel in **pinned**, change the description of that channel to include their name because absolute majority just don't check **pinned**. People also don't claim channels as frequently so there shouldn't be an issue with API limits.
2. As soon as the channel is claimed automatically append something like `(asker)` or `(seeker)` to the name of a person so it's clear for everyone who requires the help (until the channel is closed).
3. Make a role with a noticeably different colour / fitting name and give it to users who claim the channels until the channel is closed. 

Either will make it easier to understand who requires the help in a claimed channel. Or better yet combining some.

**Comment by Den4200** [comment]
The first suggestion is unfeasible - the rate limit is twice per ten
minutes. As for the name change and role, sometimes the helpees are helpers
in other channels. This would lead to confusion.

**Comment by mudkipdev** [comment]
1. As Den4200 said, the ratelimit is 2 / 5 minutes, which makes it impossible.
2. That also means they would have a nickname in other channels.
3. That also means they would have a role in other channels.

There is no real way to fix this issue, as far as I can think of.

**Comment by ChrisLovering** [comment]
Is their 3rd solution an issue? I don't see why showing a user has a help channel open could cause a problem.
You could even include the help channel name in the role to reduce confusion.

**Comment by swfarnsworth** [comment]
We could have the bot say "<x user> claimed this channel!".

**Comment by Inheritanc-e** [comment]
And where would we have that?

**Comment by swfarnsworth** [comment]
@Inheritanc-e either immediately before or immediately after pinning the original comment. So it would be in the chat.

**Comment by Inheritanc-e** [comment]
I mean that would kinda be useless as the pinned comment already shows shows who has claimed the channel.

**Comment by swfarnsworth** [comment]
If the user deletes their original comment, only mods or admins (mostly admins) have the tooling to figure out who the bot thinks the claimant is, but it would still be annoying to do in many cases. If the original comment is still there, then it's clear who the help channel claimant is and there's no problem.

**Comment by mudkipdev** [comment]
Don't see how that would fix anything. The "x claimed this channel" will just be drowned in the message history. You would have to scroll up to the point where the help channel was claimed (which may be long ago) to see. (which I would argue a lot of people won't do)

**Comment by ChrisLovering** [comment]
What's the actual problem we're trying to solve with this? Is it to help with people unintentionally trying to take over someone else's help channel? If so, maybe adding a command that says something like `This is <user>'s channel, see #how-to-get-help to claim your own` would be useful?

**Comment by jb3** [comment]
We discussed this in a staff meeting and none of the discussed solutions gathered enough support for us to implement.

If this becomes a problem where the cost of implementing a solution is worth it then we'll revisit the issue, but for now there isn't a solution where the cost outweighs the benefits or potential drawbacks of said solution.
