### ISSUE TITLE
what-are-gurkans

### ISSUE THREAD

**Issue by ChiliPy** [python-discord/meta#77]

**Comment by zeeshanok** [comment]
[I honestly don't know](https://gurkult.com/)

**Comment by swfarnsworth** [comment]
One of our staff members has the nickname Vestergurkan, and I believe people are just appending "gurkan" to their names for fun.

Or is this an OT name suggestion?

**Comment by ChiliPy** [comment]
It's supposed to be an OT name suggestion, but I wasn't sure how to get it to the correct catagory

**Comment by swfarnsworth** [comment]
@ChiliPy you should be able to leave comments in #8, which is the OT name suggestion issue.

**Comment by ReneganRonin** [comment]
@ChiliPy it is the best open sauce group in the universe.

**Comment by Akarys42** [comment]
Added!
