### ISSUE TITLE
Suggestion: Creating a channel for selecting team members for do projects as a team

### ISSUE THREAD

**Issue by StoneSteel27** [python-discord/meta#79]
Certain projects require a team of people with different skillsets to work together on an idea or problem. The landing area for these types of projects would be amazingly helpful!

I think it would be a really cool idea to create a channel for organizing teams and finding teammates for projects. It would provide an easier way to do this than trying to post on the developer chat and hope someone replies or searching for people who are looking for a teammate or asking “do you need a teammate” in general chat.

We could use a **python-team channel** for selecting team members to do python projects as a team. For example, if I want to create a python flask or Django website, I can post in the channel and anyone interested can respond to me there. 
Ethics: Channel will need to be open 24/7 and moderated constantly because people might not be able to access it at all times of the day so they might get left waiting for hours or days before someone notices.

And I know that a channel named open-source-collaboration, with the same motive was closed because of inactivity and use of it for posting ads, But for a day people started to ask for members who are interested in their project are increasing.

Also by this, newbie coders will know how to **share their work**, and **work efficiently** and **understand the value of teamwork**.

I hope they bring up this channel into existence

Thank you

**Comment by swfarnsworth** [comment]
As we discussed, we had channels such as these in the past and removed them in August. For your reference, here is what lemon wrote when we decided to delete those channels:

> The general consensus is that #show-your-projects serves three purposes:
> A) People want to share something they are excited about completing, and want some sort of acknowledgement
> B) People want to share a project to get technical feedback (like a code review).
> C) Advertising something.
> 
> Generally, we don't want people advertising things. For technical reviews, it would be better that people share their project in a help channel and ask for a code review.
> 
> For A, we don't believe #show-your-projects currently gives a lot of acknowledgement, so it feels like a lot of people will be walking away disappointed if that's their motivation. It would be much better that these members share their projects in #python-general, in an off-topic channel, or in a subreddit.
> 
> We will explain all of this in a message in #show-your-projects, and then announce that we will be closing it on September 1st. Until then, the channel will be read-only.
> 
> We will be nuking #show-your-projects-discussion.
> 

The decision to remove these channels was unanimous.

Again, this is entirely for your reference. Our past decision on this topic doesn't preclude us from reconsideration. Thank you for showing interest in the community and taking the time to write this.

**Comment by StoneSteel27** [comment]
I would ask to go for a trial of one week. We would see the results that how many people are using it properly, and by far now, no one is posting ads even in off-topic channels.
 So we should give it a go (at least a trial for one week).

**Comment by ChrisLovering** [comment]
If something like #show-your-projects is making a come back, then possibly some level of self-moderation could be considered? Maybe an emoji that gets tagged to every post, if it hits X number of votes the post gets hidden, awaiting mod action?

**Comment by StoneSteel27** [comment]
After thinking about the consequences, I should say that the team selecting channel is for selecting people for like game jams, code jams, and code exhibitions, in simpler words, only for **team selecting for events which have been officially announced** and not for personal projects, as many people could make their job work or school work as personal projects.

**Comment by SebastiaanZ** [comment]
To me, the proposed channel sounds a lot more like the `#open-source-collaboration` channel we had than `#show-your-projects`. Unfortunately, the collaboration channel was rarely used for its purpose and put a lot of pressure on the moderation team, as most activity was either off-topic or just blatant advertisement/recruitment.

I'm not inclined to bring it back in trial form, as we've experimented with the channel for a few months and it did not work out as we'd hoped.

**Comment by jb3** [comment]
As was pointed out, we've variations of this channel and none have worked out.

Moderating such a channel becomes a huge task very quickly, while we operated `#open-source-collaboration` and `#show-your-projects` a significant portion of our moderator capacity had to focus at removing posts that were low quality or in violation of our rules.

Therefore at this point we're not interested in implementing a specific channel for this, however as with project sharing members are welcome to discsuss their project in our off topic section with the goal of attracting contribution.
