### ISSUE TITLE
New Neural network dedicated channel 

### ISSUE THREAD

**Issue by RAHUL13-13** [python-discord/meta#80]
Please create neural network dedicated channel as there is difficulty in finding help

**Comment by gustavwilliam** [comment]
We already have #data-science for discussing things like scientific python, matplotlib, statistics, machine learning and related topics. Hope that helps 😄

**Comment by jb3** [comment]
As stated by @gustavwilliam this is already a topic which comes under the scope of our `#data-science` channel (and is used fairly frequently for such topics — there are resources pinned there).

Splitting channels out causes confusion about which topic belongs where so it's most simple and most effective in the current configuration.

The overlap between `#data-science` and a neural network channel is vast so there is no need for an additional channel at this point.
