### ISSUE TITLE
Feature: SelfBot Filter 

### ISSUE THREAD

**Issue by ChiliPy** [python-discord/meta#83]
SelfBot filter

The filter is simple. Check if a message has an embed, and check if the author of the message is a normal user account. An example of how this would work is something like this

async def on_message(message):
    if len(message.embeds) >= 1 and not message.author.bot:
        message_staff_channel

I think this would be a good addition because it provides a really simple, yet, really effective system for finding self bots. At the moment, the only way to find self bots is for a staff/user to see it, and report/take action on it. This is a problem because there are so many message sent per minute that the self bots message can get lost in everyone else's, therefor making it almost
Impossible to actually find them.

Implementation of this filter would be relatively easy. All that's required is to write the one event in a cog, load the cog, and voila. There is a lot gained with nothing lost in this idea. We get TOS violators out for PyDis easily, and 0 false positives.

**Comment by mbaruh** [comment]
Sorry, I should have been clearer. We already have a measure like that in the bot :)

**Comment by jb3** [comment]
This feature is already implemented in the mod alerts system, but we appreciate you looking to simplify our job! 😃
