### ISSUE TITLE
Channel: Code advice/review

### ISSUE THREAD

**Issue by Xpl0itU** [python-discord/meta#84]
# What is the channel about?

As the name implies, the channel is about people sharing their repos/snippets of code and asking what they think of it or if someone could be done better

# Justification

Sometimes you don’t want help on something, but maybe you want suggestions or opinions that can help improve your code or learn how to do something differently

**Comment by jb3** [comment]
Our policy for code reviews has always been that opening a help channel is completely fine for this sort of discussion. I don't think that the amount of traffic which code review questions constitute warrant a new channel.

As was noted in the meta channel while discussing this issue there should be no worrying about whether a question is "worth" opening a help channel, we introduced the dynamic help channel system to be able to cope with many more questions at once (we can now handle dozens at a time!) which will close after 30 minutes of inactivity.

Therefore, I'm going to close this issue. We already encourage the use of the help channels for code reviews, and the help channels are a much better medium for this kind of discussion.
