### ISSUE TITLE
Feature: Index the rules for 0

### ISSUE THREAD

**Issue by GDWR** [python-discord/meta#87]
# What?

Change the rules to start at 0

# Justification

Since this is a programming server, its more natural to start everything at 0.

# Implementation

CTRL+A, CTRL+C -> Change the numbers to their current value -1 -> CTRL+V -> Job good 👍

**Comment by GDWR** [comment]
Thank you for the edit Laundmo, it really makes the request stand out!

**Comment by lemonsaurus** [comment]
Hey, thanks for making an issue about this!

We're currently displaying our rules both in the Discord native gate (the thing new members see when they join), and on our website, #rules channel, and !rules command. We _could_ change this in the latter three places, but it's impossible to set a Rule #0 in the native gate.

We don't want our rules numbers to be inconsistent across the different places where they're visible, so we're not gonna do this, even though we appreciate the joke.
