### ISSUE TITLE
Feature: User's with an open help channel have a role with the help channel name

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/meta#89]
# What?

When a user opens a help channel, they get assigned a role with that help channel's name. When their help channel closes, this role is removed.

We could also have this role change the colour of their name, so that other users are aware they currently have a help channel open. (Side benefit of this is that the user who opened the help will be highlighted in the channel)

# Justification

New users sometimes lose their help channel and can't find their way back, so post in another help channel instead. Having the help channel in a role could help users direct them to their own help channel.

# Implementation

Enhancement to the help channel functionality in `@Python`. We can add the role at the same time (same API call) as we add the help channel cooldown role.

Removing the role needs some though. Currently, the help cooldown isn't removed on close, but rather after a set period of time.

@Akarys42 Also pointed out that this could add a lot of noise to the role tab, so Admins would need to be happy that this change doesn't impact them too much.

**Comment by jb3** [comment]
This was discussed in the meeting and we decided that adding a role to a user is unlikely to help themm find their own help channel. As well as this the roles UI in Discord is already slow for administrators, so adding more roles would not help.

Instead, we decided to focus on existing attempted solutios at this such as python-discord/bot#1174. If this does not pan out we'll revisit this idea.
