### ISSUE TITLE
Channel: packaging

### ISSUE THREAD

**Issue by cjauvin** [python-discord/meta#90]
# What is the channel about?

A place to discuss and ask help about Python packaging issues and related topics: pip, setuptools, etc.

# Justification

I have been a new user on Python Discord for a couple of weeks now and I have been surprised to discover that there is no dedicated channel for such an important and central topic in the Python world. I for one would certainly use it regularly. There is already the #tools-and-devops channel but I feel that packaging would deserve its own space, given its importance.

**Comment by jb3** [comment]
We've discussed this in our staff meeting and felt that a packaging specific channel would not generate enough traffic. However, it's important to facilitate a place where said topics are more accessible.

Therefore, we've instead introduced a new `#editors-ides` channel to reduce load on `#tools-and-devops`. We've also explicitly listed packaging tools in the description of the tools and devops channel.

Hopefully the reduced traffic on the tools and devops channel will mean that packaging questions are more likely to be asked and answered.
