### ISSUE TITLE
More Voice Channels

### ISSUE THREAD

**Issue by ForbiddenKJ** [python-discord/meta#91]
# Issue

There are too little voice chats, it's only nice to have a conversation / discussion when there are 6 or less people in a voice channel. This is because too many people are trying to interject their opinion and having conversations and it's hard speaking when there are a so many people talking over each other.

# Justification

The voice chats often fill up in peak times and its just annoying, you are unable to get a word out and discussion become derailed. It's hard to talk and to have a conversation when there are 6+ people trying to speak, it just becomes too damn noisy. The conversations are no longer fun or interesting because everybody is trying to join in. If there were more voice channels it would be easier to have an actual conversation with group of people. Although this is not usually an issue, even if more voice channels were opened when there are X amount of people in a voice channel this would benefit the community greatly because they have options to move to a less noisy channel with less people in and have civilised conversation.

**Comment by HassanAbouelela** [comment]
Active voice channels actively draw more people in. Looking at the channels right now, there is one with 11 people, and one with 1.

How would adding another channel to the list change that, when people will simply continue using the more active ones.

Either way, I’ll be curious to see @MrHemlock opinion on this.

**Comment by ForbiddenKJ** [comment]
![talk](https://user-images.githubusercontent.com/36408549/108600249-10d6e080-738e-11eb-895d-84f3c8ca3165.JPG)

**Comment by ForbiddenKJ** [comment]
![talk](https://user-images.githubusercontent.com/36408549/108602682-361e1b80-739b-11eb-9278-287b1b799cb4.JPG)

**Comment by Akarys42** [comment]
Hello @ForbiddenKJ, why are you posting those screenshots?

**Comment by MrHemlock** [comment]
During the weekdays (which is when I'm mostly active on the voice channels), we typically see a user count of 15 to 20 in one channel and no people in the other one.  Within that main channel, we typically have around 6 or so people talking, with a majority listening or participating by typing in the voice text chats.  

I'm not opposed to the idea of having another channel, but I have yet to truly see a time when we've really needed it.  And for the sake of keeping channel clutter down, I'd prefer to not add more channels than we need.

@ForbiddenKJ can you elaborate when these peak times are?  By that I mean if it's happening on a specific day or section of the week or time of day.  It would be helpful to see when it's happening and with how many people.

**Comment by ForbiddenKJ** [comment]
@MrHemlock I haven't been here long enough to tell you at what point of the week this occurs, and it is not a common occurrence, I have seen this 2/3 times in the last 2 weeks I have been using the vc's although this is not a typical week due to the nasa landing I think it would just be a good idea for channels to be automatically added/enabled if channel do happen to be start to fill up. This should have been in feature requests, my apologies.

**Comment by jb3** [comment]
Having observed the usage of voice channels for the past week I don't think it's necessary at this point to add more.

Adding more voice channels does not solve this problem, because people simply want to be in the voice channel where the most interesting conversation is going on, adding more just means you have a voice channel that is overused and all the rest see little to no usage, so the benefits do not outweigh the costs of an increase in moderation required.

We'll revisit this issue with the Voice Lead if we reach a point where there are major issues occurring, but even at peak times the majority of voice participants are listeners (as Hemlock notes, 6 or so people are talking at once even in a full channel).
