### ISSUE TITLE
Increase aviable help channels

### ISSUE THREAD

**Issue by OpenPiece** [python-discord/meta#92]
# Justification
There are currently 2 help channels in the available category, this is often insufficient because many times when I try to ask a question, I can see that in both of these channels, someone is already typing there. 

This isn't necessarily a huge issue, but many times, when I finish typing first, the user who was already typing doesn't notice that the channel is now claimed, and proceeds to send his question. Increasing the amount of available channels at all time would give users an opportunity to pick a channel where nobody will be typing already.

This can either be done in some kind of dynamic way, where the bot could detect typing in these channels and if both are being typed into at the same time, send a new channel in, or in a static way, by simply increasing the amount of channels to 3 or 4.

**Comment by PureFunctor** [comment]
This sounds like a good idea considering the current growth of our community; we typically discuss channel changes such as these in staff meetings before trialing them for a short time, eventually leading into said change either being reverted or made permanent.

> where the bot could detect typing in these channels and if both are being typed into at the same time, send a new channel in

For what it's worth, I think we've had similar suggestions in the past although I don't think we've followed through with it yet; I guess the core devs for our bot would most likely know.

**Comment by jb3** [comment]
We've agreed to do this and increase the available channels to 3.

Further discussion of this can take place at python-discord/bot#1427.
