### ISSUE TITLE
Channel: Roles

### ISSUE THREAD

**Issue by janine9vn** [python-discord/meta#97]
# What is the channel about?
Listing of our roles and *brief* descriptions of them. It would also include a link to our webpage that describes them in more details. This channel would be under the "Information" category, under `#code-of-conduct`

# Justification
It's typical for servers to have a "roles" channel to describe all the roles on the server and their general purpose. While we do have this outlined on our website, for people who aren't familiar with our community it's not obvious that a) we even have a website and b) that is the place to check for discord roles. I don't think it costs us much to add this channel and would be helpful for people who are not new to discord but are new to our community.

**Comment by swfarnsworth** [comment]
I'd rather not have identical information that is likely to change over time in two places. Is there a way we can make it easier for people to find the role descriptions on the website?

I see that the channel description for community-meta doesn't link to the FAQ. Can that be added?

**Comment by janine9vn** [comment]
So this is what a potential roles channel could look like:
![image](https://user-images.githubusercontent.com/20641196/118344526-7d302e80-b4fc-11eb-988c-e10e40a7c07f.png)

For quick reference, roles page on the website: https://pythondiscord.com/pages/server-info/roles/

Personally I think it's a better experience for discord users if there's a channel explaining the roles rather than them having to go off server to find the details. We already maintain the rules and code of conduct in two places, I think the roles channel would be nice to have as well.

**Comment by Akarys42** [comment]
I think this would be a good addition, it is way easier to find and could avoid some "How to get helper" questions. Also, the gradient looks good, you gotta give it that.

**Comment by Objectivitix** [comment]
I agree, visually appealing and useful

**Comment by janine9vn** [comment]
This is now a channel!
