### ISSUE TITLE
Resource: A new Project Idea page made by Python Discord

### ISSUE THREAD

**Issue by dawnofmidnight** [python-discord/meta#99]
# What resource?
Using `!projects`, we always link to the project page on Nedbat's website. Ned's website is wonderful, but I think it would also be nice for PyDis to make our own list too. I think that would allow us to have a nice variety of project ideas, especially if the community can contribute ideas for a list..

# Locations
I thnk a page on the PyDis website similar to the [resources](https://pythondiscord.com/pages/resources/) page would be nice. It would be easily accessible for people to see, and we could also link that page through `!projects`.

# Justification
This would allow us to have more variety in the project ideas, which is nice since we've been using the same one for quite a while. I think we should still keep Nedbat's list, just add this as another resource.

**Comment by janine9vn** [comment]
So after discussion during the staff meeting we felt as though we shouldn't necessarily solve a problem that already has a good solution (i.e. Ned Bat's list). 

I think we could link to nedbat's page on the website (although that will have to wait a bit) and if we want to add projects to that list, we can suggest links or project ideas to his website directly: https://nedbatchelder.com/text/kindling.html (https://github.com/nedbat/nedbatcom)

**Comment by dawnofmidnight** [comment]
Makes complete sense, thanks for considering it!
